import { Link } from 'react-router-dom';
/* Images generated by AI */
import heroDashboardImg from '/images/menukits-dashboard.svg';
import phoneMenuImg from '/images/A_smartphone_screen_showing_an_2026-05-26T12-52-24.png';
import foodCollageImg from '/images/Beautiful_AI_generated_profess_2026-05-26T12-52-36.png';
import foodGridImg from '/images/Four_square_AI_food_photos_arr_2026-05-26T12-53-27.png';
import qrTableImg from '/images/A_chef_s_hand_placing_a_QR_cod_2026-05-26T12-52-18.png';
import {
  ArrowRight,
  Check,
  QrCode,
  Smartphone,
  Monitor,
  Camera,
  Globe,
  Zap,
  Shield,
  ChevronDown,
  Menu,
  X,
  Sparkles,
  MessageCircle,
  UtensilsCrossed,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useState } from 'react';

/* ------------------------------------------------------------------ */
/*  Navbar                                                            */
/* ------------------------------------------------------------------ */
function Navbar() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-100">
      <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
        {/* Logo */}
        <Link to="/" className="flex items-center gap-1.5 shrink-0 cursor-pointer">
          <UtensilsCrossed className="h-6 w-6 text-[#f5b800]" />
          <span className="text-xl font-bold tracking-tight text-[#1a1520]">Menu</span>
          <span className="text-xl font-bold tracking-tight text-[#f5b800]">kits</span>
        </Link>

        {/* Desktop links */}
        <div className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-600">
          {['Features', 'Pricing', 'FAQ'].map((item) => (
            <a
              key={item}
              href={`#${item.toLowerCase()}`}
              className="transition-colors hover:text-[#5544e4] cursor-pointer"
            >
              {item}
            </a>
          ))}
        </div>

        {/* Right actions */}
        <div className="flex items-center gap-3 shrink-0">
          <Link to="/app">
            <Button variant="ghost" size="sm" className="hidden sm:inline-flex text-sm font-medium text-gray-600 hover:text-[#5544e4]">
              Log in
            </Button>
          </Link>
          <Link to="/app">
            <Button
              size="sm"
              className="bg-[#5544e4] text-white hover:bg-[#4433cc] text-sm font-semibold px-5"
            >
              Get started
            </Button>
          </Link>

          {/* Mobile menu toggle */}
          <button
            onClick={() => setMobileOpen(!mobileOpen)}
            className="md:hidden p-2 text-gray-600 hover:text-[#5544e4]"
          >
            {mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>
      </div>

      {/* Mobile dropdown */}
      {mobileOpen && (
        <div className="md:hidden border-t border-gray-100 bg-white px-4 py-4 space-y-3">
          {['Features', 'Pricing', 'FAQ'].map((item) => (
            <a
              key={item}
              href={`#${item.toLowerCase()}`}
              className="block py-2 text-sm font-medium text-gray-600"
            >
              {item}
            </a>
          ))}
          <div className="pt-2 border-t border-gray-100">
            <Link to="/app" className="text-sm font-medium text-gray-600 block py-2">Log in</Link>
          </div>
        </div>
      )}
    </nav>
  );
}

/* ------------------------------------------------------------------ */
/*  Hero section                                                      */
/* ------------------------------------------------------------------ */
function HeroSection() {
  return (
    <section className="relative pt-32 pb-20 landing-hero-bg overflow-hidden">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 text-center">
        {/* Badge */}
        <div className="inline-flex items-center gap-2 rounded-full bg-[#5544e4]/8 border border-[#5544e4]/15 px-4 py-1.5 mb-8">
          <Sparkles className="h-4 w-4 text-[#5544e4]" />
          <span className="text-xs sm:text-sm font-medium text-[#5544e4]">
            The #1 QR menu builder platform
          </span>
        </div>

        {/* Headline */}
        <h1 className="text-4xl sm:text-5xl lg:text-6xl xl:text-7xl font-extrabold tracking-tight text-gray-900 leading-[1.08] mb-6">
          Create your digital QR menu{' '}
          <br className="hidden sm:block" />
          in <span className="landing-gradient-text">minutes</span>
        </h1>

        {/* Subtitle */}
        <p className="max-w-2xl mx-auto text-base sm:text-lg lg:text-xl text-gray-500 leading-relaxed mb-10">
          Transform your restaurant's dining experience with beautiful, interactive QR menus.
          No coding required. Update your menu instantly, anytime.
        </p>

        {/* CTA buttons */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
          <Link to="/app">
            <Button
              size="lg"
              className="bg-[#5544e4] hover:bg-[#4433cc] text-white font-semibold px-8 py-6 text-lg rounded-xl shadow-lg shadow-[#5544e4]/25 transition-all hover:shadow-xl hover:shadow-[#5544e4]/30 hover:-translate-y-0.5"
            >
              Get started for free
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
          <a href="#features">
            <Button
              variant="outline"
              size="lg"
              className="border-gray-300 text-gray-700 font-semibold px-8 py-6 text-lg rounded-xl hover:bg-gray-50 transition-colors"
            >
              See how it works
            </Button>
          </a>
        </div>

        {/* Hero image - dashboard screenshot */}
        <div className="relative max-w-4xl mx-auto">
          <div className="rounded-2xl shadow-2xl shadow-gray-200/50 border border-gray-200 bg-white overflow-hidden">
            <img
              src={heroDashboardImg}
              alt="menukits Dashboard - Create and manage your QR menus"
              className="w-full h-auto"
            />
          </div>

          {/* Floating elements */}
          <div className="absolute -left-4 top-1/3 hidden lg:block">
            <div className="bg-white rounded-xl shadow-lg border border-gray-100 p-4 animate-pulse" style={{ animationDuration: '3s' }}>
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center">
                  <Check className="h-5 w-5 text-green-600" />
                </div>
                <div>
                  <div className="text-xs font-semibold text-gray-900">Menu updated!</div>
                  <div className="text-[11px] text-gray-500">Live now</div>
                </div>
              </div>
            </div>
          </div>

          <div className="absolute -right-4 bottom-1/4 hidden lg:block">
            <div className="bg-white rounded-xl shadow-lg border border-gray-100 p-4 animate-pulse" style={{ animationDuration: '4s', animationDelay: '1s' }}>
              <QrCode className="h-10 w-10 text-[#5544e4] mx-auto mb-2" />
              <div className="text-xs font-semibold text-gray-900 text-center">Scan me</div>
            </div>
          </div>
        </div>

        {/* Social proof */}
        <div className="mt-10 flex flex-wrap items-center justify-center gap-x-8 gap-y-3 text-sm text-gray-400">
          <span className="flex items-center gap-1.5">
            <Check className="h-4 w-4 text-green-500" /> Free forever plan
          </span>
          <span className="flex items-center gap-1.5">
            <Check className="h-4 w-4 text-green-500" /> No credit card required
          </span>
          <span className="flex items-center gap-1.5">
            <Check className="h-4 w-4 text-green-500" /> Setup in 2 minutes
          </span>
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Features intro banner                                             */
/* ------------------------------------------------------------------ */
function FeatureBanner() {
  return (
    <section id="features" className="py-20 bg-[#f0eeff]">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 text-center">
        <div className="inline-block bg-[#fbbf24] text-gray-900 text-xs font-bold uppercase tracking-wide px-3 py-1 rounded-full mb-6">
          Why menukits?
        </div>
        <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 leading-tight mb-4">
          Create your menu in minutes, for every{' '}
          <span className="font-serif italic font-normal text-gray-600">foodtruck</span>
        </h2>
        <p className="max-w-2xl mx-auto text-gray-500 text-base sm:text-lg">
          From cozy cafes to fine dining restaurants — our platform adapts to your needs.
        </p>

        {/* Feature cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mt-14">
          {[
            {
              icon: QrCode,
              title: 'Instant QR codes',
              desc: 'Generate scannable QR codes for every table. Customers view your menu instantly.',
            },
            {
              icon: Smartphone,
              title: 'Mobile-first design',
              desc: 'Beautiful menus that look perfect on any device. Optimized for smartphones.',
            },
            {
              icon: Monitor,
              title: 'Real-time updates',
             _desc: 'Change prices or dishes and see updates live immediately across all devices.',
            },
            {
              icon: Globe,
              title: 'Multi-language support',
              desc: 'Auto-translate your menu into 50+ languages to serve international guests.',
            },
          ].map((feat) => (
            <div
              key={feat.title}
              className="group bg-white rounded-2xl p-6 sm:p-7 text-left border border-gray-100 hover:border-[#5544e4]/20 hover:shadow-lg transition-all duration-300 cursor-pointer"
            >
              <div className="w-12 h-12 rounded-xl bg-[#5544e4]/8 group-hover:bg-[#5544e4]/12 flex items-center justify-center mb-4 transition-colors">
                <feat.icon className="h-6 w-6 text-[#5544e4]" />
              </div>
              <h3 className="text-base font-bold text-gray-900 mb-2">{feat.title}</h3>
              <p className="text-sm text-gray-500 leading-relaxed">{feat.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Split feature sections                                            */
/* ------------------------------------------------------------------ */

function SplitFeatureLeft() {
  return (
    <section className="py-20 sm:py-28 bg-white">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-center">
          {/* Text side */}
          <div>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 leading-tight mb-6">
              Create your digital QR menu in minutes
            </h2>
            <p className="text-gray-500 text-base leading-relaxed mb-8">
              Our intuitive drag-and-drop editor lets you build stunning menus without any technical skills.
              Choose from professional templates, customize colors, add photos, and go live instantly.
            </p>
            <ul className="space-y-4">
              {[
                'Drag & drop menu editor',
                'Professional templates included',
                'AI-powered food photography',
                'Auto-translate to 50+ languages',
              ].map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <div className="mt-0.5 w-5 h-5 rounded-full bg-[#5544e4]/10 flex items-center justify-center shrink-0">
                    <Check className="h-3 w-3 text-[#5544e4]" />
                  </div>
                  <span className="text-gray-700 text-sm">{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Image side - phone mockup with real image */}
          <div className="relative flex justify-center lg:justify-end">
            <div className="relative w-56 sm:w-64 lg:w-72">
              <div className="rounded-3xl shadow-2xl overflow-hidden border border-gray-200">
                <img
                  src={phoneMenuImg}
                  alt="Digital menu preview on smartphone"
                  className="w-full object-cover"
                />
              </div>
              {/* Decorative circle */}
              <div className="absolute -z-10 -top-6 -right-6 w-48 h-48 bg-[#5544e4]/5 rounded-full blur-2xl" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function SplitFeatureRight() {
  return (
    <section className="py-20 sm:py-28 bg-gray-50/70">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-center">
          {/* Image side - food photo collage */}
          <div className="relative order-2 lg:order-1">
            <div className="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
              <img
                src={foodCollageImg}
                alt="Beautiful AI-generated food photography for restaurant menus"
                className="w-full h-auto object-cover"
              />
            </div>
          </div>

          {/* Text side */}
          <div className="order-1 lg:order-2">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 leading-tight mb-6">
              A better menu experience for locals and tourists
            </h2>
            <p className="text-gray-500 text-base leading-relaxed mb-8">
              Impress your guests with a modern, interactive menu experience. High-quality images,
              clear descriptions, and instant availability updates keep everyone informed.
            </p>
            <Link to="/app">
              <Button className="bg-[#5544e4] hover:bg-[#4433cc] text-white font-semibold px-6">
                Try it free
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Photo feature                                                     */
/* ------------------------------------------------------------------ */
function PhotoFeature() {
  return (
    <section className="py-20 sm:py-28 bg-white">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-center">
          <div>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 leading-tight mb-6">
              Photos that sell. Without a photo shoot.
            </h2>
            <p className="text-gray-500 text-base leading-relaxed mb-8">
              Generate stunning, appetizing food images using AI. No expensive photo shoots needed.
              Just describe your dish and get professional-quality photos in seconds.
            </p>
            <Link to="/app">
              <Button className="bg-[#5544e4] hover:bg-[#4433cc] text-white font-semibold px-6">
                Get Started
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
          <div className="relative">
            <div className="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
              <img
                src={foodGridImg}
                alt="AI-generated food photography showcase - gourmet dishes"
                className="w-full h-auto object-cover"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  How it works (dark)                                              */
/* ------------------------------------------------------------------ */
function HowItWorks() {
  return (
    <section className="py-20 sm:py-28 bg-[#1a1642] text-white relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0 opacity-30">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-[#5544e4] rounded-full blur-[120px]" />
        <div className="absolute bottom-0 right-1/4 w-72 h-72 bg-purple-500 rounded-full blur-[100px]" />
      </div>

      <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
        <div className="inline-block bg-[#fbbf24] text-gray-900 text-xs font-bold uppercase tracking-wide px-3 py-1 rounded-full mb-6">
          Simple process
        </div>
        <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-16">
          How does it work?
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          {[
            {
              num: '01',
              title: 'Create your menu',
              desc: "Sign up and use our intuitive editor to build your digital menu. Add dishes, descriptions, prices, and photos. It takes less than 5 minutes.",
            },
            {
              num: '02',
              title: 'Customize & brand',
              desc: "Match your restaurant's identity with custom colors, fonts, and layouts. Add your logo and create a seamless brand experience.",
            },
            {
              num: '03',
              title: 'Print & share QR',
              desc: 'Download unique QR codes for each table. Print them as coasters, table tents, or stickers. Your menu goes live instantly when scanned.',
              image: qrTableImg,
            },
          ].map((step) => (
            <div key={step.num} className="group">
              <div className="text-6xl font-black text-white/10 group-hover:text-white/20 transition-colors mb-4">
                {step.num}
              </div>
              <h3 className="text-xl font-bold mb-3">{step.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed mb-4">{step.desc}</p>
              {(step as any).image && (
                <img
                  src={(step as any).image}
                  alt={step.title}
                  className="rounded-xl w-full object-cover shadow-lg"
                />
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Pricing                                                          */
/* ------------------------------------------------------------------ */
function PricingSection() {
  return (
    <section id="pricing" className="py-20 sm:py-28 bg-[#f5f4ff]">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 text-center">
        <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">Pricing</h2>
        <p className="text-gray-500 max-w-lg mx-auto mb-14">
          Start free, upgrade when you need more power. No hidden fees.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 lg:gap-8 items-start">
          {/* Free */}
          <div className="bg-white rounded-2xl p-7 sm:p-8 border border-gray-200 text-left hover:shadow-lg transition-shadow">
            <div className="mb-6">
              <h3 className="text-lg font-bold text-gray-900 mb-1">Starter</h3>
              <p className="text-xs text-gray-500">Perfect for trying out</p>
            </div>
            <div className="mb-6">
              <span className="text-4xl font-extrabold text-gray-900">$0</span>
              <span className="text-gray-500 text-sm ml-1">/month</span>
            </div>
            <ul className="space-y-3 mb-8">
              {['1 menu', 'Up to 20 items', 'Basic template', 'QR code generation', 'Mobile preview'].map((f) => (
                <li key={f} className="flex items-start gap-2.5 text-sm text-gray-600">
                  <Check className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                  {f}
                </li>
              ))}
            </ul>
            <Link to="/app" className="block">
              <Button variant="outline" className="w-full border-gray-300 font-semibold hover:bg-gray-50">
                Get started
              </Button>
            </Link>
          </div>

          {/* Pro - highlighted */}
          <div className="bg-[#5544e4] rounded-2xl p-7 sm:p-8 text-left shadow-xl shadow-[#5544e4]/20 relative">
            <div className="absolute -top-3 left-1/2 -translate-x-1/2">
              <span className="bg-[#fbbf24] text-gray-900 text-[10px] font-bold uppercase tracking-wide px-3 py-1 rounded-full">
                Most Popular
              </span>
            </div>
            <div className="mb-6">
              <h3 className="text-lg font-bold text-white mb-1">Pro</h3>
              <p className="text-xs text-indigo-200">For growing restaurants</p>
            </div>
            <div className="mb-6">
              <span className="text-4xl font-extrabold text-white">$19</span>
              <span className="text-indigo-200 text-sm ml-1">/month</span>
            </div>
            <ul className="space-y-3 mb-8">
              {[
                'Unlimited menus',
                'Unlimited items',
                'All premium templates',
                'AI food photography',
                'Multi-language (50+)',
                'Analytics dashboard',
                'Custom branding',
                'Priority support',
              ].map((f) => (
                <li key={f} className="flex items-start gap-2.5 text-sm text-indigo-100">
                  <Check className="h-4 w-4 text-indigo-300 mt-0.5 shrink-0" />
                  {f}
                </li>
              ))}
            </ul>
            <Link to="/app" className="block">
              <Button className="w-full bg-white text-[#5544e4] font-bold hover:bg-gray-100">
                Start free trial
              </Button>
            </Link>
          </div>

          {/* Business */}
          <div className="bg-white rounded-2xl p-7 sm:p-8 border border-gray-200 text-left hover:shadow-lg transition-shadow">
            <div className="mb-6">
              <h3 className="text-lg font-bold text-gray-900 mb-1">Business</h3>
              <p className="text-xs text-gray-500">For chains & large venues</p>
            </div>
            <div className="mb-6">
              <span className="text-4xl font-extrabold text-gray-900">$49</span>
              <span className="text-gray-500 text-sm ml-1">/month</span>
            </div>
            <ul className="space-y-3 mb-8">
              {[
                'Everything in Pro',
                'Multi-location management',
                'Team collaboration',
                'API access',
                'White-label option',
                'Dedicated account manager',
              ].map((f) => (
                <li key={f} className="flex items-start gap-2.5 text-sm text-gray-600">
                  <Check className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                  {f}
                </li>
              ))}
            </ul>
            <Link to="/app" className="block">
              <Button variant="outline" className="w-full border-gray-300 font-semibold hover:bg-gray-50">
                Contact sales
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Contact                                                           */
/* ------------------------------------------------------------------ */
function ContactSection() {
  return (
    <section className="py-20 sm:py-28 bg-white">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
          <div>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
              Contact us for more information
            </h2>
            <p className="text-gray-500 leading-relaxed mb-8">
              Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.
            </p>
            <div className="space-y-4">
              {[
                { label: 'Email', value: 'hello@menukits.eu' },
                { label: 'Response time', value: 'Usually within 2 hours' },
              ].map((info) => (
                <div key={info.label}>
                  <dt className="text-sm font-medium text-gray-400">{info.label}</dt>
                  <dd className="text-gray-900 font-medium">{info.value}</dd>
                </div>
              ))}
            </div>
          </div>
          <form className="space-y-4" onSubmit={(e) => e.preventDefault()}>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <input
                type="text"
                placeholder="Name"
                className="w-full rounded-xl border border-gray-200 bg-gray-50/80 px-4 py-3 text-sm placeholder:text-gray-400 focus:border-[#5544e4] focus:outline-none focus:ring-2 focus:ring-[#5544e4]/10 transition"
              />
              <input
                type="email"
                placeholder="Email"
                className="w-full rounded-xl border border-gray-200 bg-gray-50/80 px-4 py-3 text-sm placeholder:text-gray-400 focus:border-[#5544e4] focus:outline-none focus:ring-2 focus:ring-[#5544e4]/10 transition"
              />
            </div>
            <textarea
              rows={4}
              placeholder="Your message..."
              className="w-full rounded-xl border border-gray-200 bg-gray-50/80 px-4 py-3 text-sm placeholder:text-gray-400 focus:border-[#5544e4] focus:outline-none focus:ring-2 focus:ring-[#5544e4]/10 transition resize-none"
            />
            <Button
              type="submit"
              className="w-full bg-[#5544e4] hover:bg-[#4433cc] text-white font-semibold py-5 rounded-xl"
            >
              Send message
            </Button>
          </form>
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  FAQ                                                               */
/* ------------------------------------------------------------------ */
function FAQSection() {
  const [openIdx, setOpenIdx] = useState<number | null>(null);

  const faqs = [
    { q: 'Is there really a free plan? How long does it last?', a: 'Yes! Our Starter plan is completely free forever, no credit card required. It includes 1 menu with up to 20 items.' },
    { q: 'How quickly can I set up my first menu?', a: 'Most users create their first menu in under 5 minutes. Just sign up, choose a template, add your dishes, and you\'re ready to go.' },
    { q: 'Can I change my pricing after publishing?', a: 'Absolutely! One of our core features is real-time updates. Change any price, description, or dish and it reflects instantly on all scanned QR codes.' },
    { q: 'Do I need to know how to code?', a: 'No coding needed at all. Our drag-and-drop editor is designed for anyone to use. If you can use a word processor, you can build a menu.' },
    { q: 'Can I use my own domain name?', a: 'Yes! On our Business plan you can use custom domains and white-label the entire experience so it matches your brand perfectly.' },
    { q: 'What if I need help getting started?', a: 'We offer comprehensive documentation, video tutorials, and responsive customer support via email and live chat. Pro and Business plans include priority support.' },
    { q: 'How secure is customer data?', a: 'We take security seriously. All data is encrypted in transit and at rest. We are GDPR compliant and never sell your data to third parties.' },
  ];

  return (
    <section id="faq" className="py-20 sm:py-28 bg-[#f5f4ff]">
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 text-center mb-4">
          Frequently Asked Questions
        </h2>
        <p className="text-gray-500 text-center mb-12">
          Everything you need to know about menukits.
        </p>

        <div className="space-y-3">
          {faqs.map((faq, idx) => (
            <div
              key={idx}
              className="bg-white rounded-xl border border-gray-200 overflow-hidden transition-shadow hover:shadow-sm cursor-pointer"
              onClick={() => setOpenIdx(openIdx === idx ? null : idx)}
            >
              <button className="w-full flex items-center justify-between p-5 text-left">
                <span className="text-sm sm:text-base font-semibold text-gray-900 pr-4">{faq.q}</span>
                <ChevronDown
                  className={`h-5 w-5 text-gray-400 shrink-0 transition-transform duration-200 ${
                    openIdx === idx ? 'rotate-180' : ''
                  }`}
                />
              </button>
              {openIdx === idx && (
                <div className="px-5 pb-5">
                  <p className="text-sm text-gray-500 leading-relaxed">{faq.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Footer                                                            */
/* ------------------------------------------------------------------ */
function Footer() {
  return (
    <footer className="bg-[#1a1642] text-white py-16">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-8 mb-12">
          {/* Brand col */}
          <div className="col-span-2 sm:col-span-1">
            <span className="text-xl font-bold tracking-tight">
              Taptop<span className="text-indigo-400">manu</span>
            </span>
            <p className="mt-3 text-sm text-gray-400 leading-relaxed">
              The modern way to share your restaurant menu with the world.
            </p>
          </div>
          {[
            {
              title: 'Product',
              links: ['Features', 'Pricing', 'Templates'],
            },
            {
              title: 'Company',
              links: ['About', 'Blog', 'Careers', 'Contact'],
            },
            {
              title: 'Legal',
              links: [
                { name: 'Privacy', href: '/privacy' },
                { name: 'Terms', href: '/terms' },
                { name: 'Cookies', href: '/cookies' },
                { name: 'Imprint', href: '/imprint' },
              ],
            },
          ].map((col) => (
            <div key={col.title}>
              <h4 className="font-semibold text-sm mb-4">{col.title}</h4>
              <ul className="space-y-2.5">
                {col.links.map((l) => (
                  <li key={l.name}>
                    <a href={l.href} className="text-sm text-gray-400 hover:text-white transition-colors cursor-pointer">
                      {l.name}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="border-t border-white/10 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-gray-500">&copy; 2026 menukits. All rights reserved.</p>
          <div className="flex items-center gap-2">
            <MessageCircle className="h-4 w-4 text-gray-500" />
            <span className="text-xs text-gray-500">Made with love for restaurants everywhere</span>
          </div>
        </div>
      </div>
    </footer>
  );
}

/* ------------------------------------------------------------------ */
/*  Main Landing Page                                                 */
/* ------------------------------------------------------------------ */
export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <main>
        <HeroSection />
        <FeatureBanner />
        <SplitFeatureLeft />
        <SplitFeatureRight />
        <PhotoFeature />
        <HowItWorks />
        <PricingSection />
        <ContactSection />
        <FAQSection />
      </main>
      <Footer />
    </div>
  );
}
