import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

/* ================================================================
   Supported Languages — 24 mainstream global languages
   European countries prioritized as requested
   ================================================================ */
export interface LangOption {
  code: string;
  label: string;
  nativeLabel: string;
  flag: string;
}

export const LANGUAGES: LangOption[] = [
  { code: 'en', label: 'English',       nativeLabel: 'English',       flag: '🇬🇧' },
  { code: 'es', label: 'Spanish',        nativeLabel: 'Español',       flag: '🇪🇸' },
  { code: 'fr', label: 'French',         nativeLabel: 'Français',      flag: '🇫🇷' },
  { code: 'de', label: 'German',         nativeLabel: 'Deutsch',       flag: '🇩🇪' },
  { code: 'it', label: 'Italian',        nativeLabel: 'Italiano',      flag: '🇮🇹' },
  { code: 'pt', label: 'Portuguese',     nativeLabel: 'Português',    flag: '🇵🇹' },
  { code: 'nl', label: 'Dutch',          nativeLabel: 'Nederlands',    flag: '🇳🇱' },
  { code: 'ru', label: 'Russian',        nativeLabel: 'Русский',       flag: '🇷🇺' },
  { code: 'zh', label: 'Chinese',        nativeLabel: '中文',          flag: '🇨🇳' },
  { code: 'ja', label: 'Japanese',       nativeLabel: '日本語',         flag: '🇯🇵' },
  { code: 'ko', label: 'Korean',         nativeLabel: '한국어',         flag: '🇰🇷' },
  { code: 'ar', label: 'Arabic',         nativeLabel: 'العربية',       flag: '🇸🇦' },
  { code: 'tr', label: 'Turkish',        nativeLabel: 'Türkçe',        flag: '🇹🇷' },
  { code: 'pl', label: 'Polish',         nativeLabel: 'Polski',        flag: '🇵🇱' },
  { code: 'sv', label: 'Swedish',        nativeLabel: 'Svenska',       flag: '🇸🇪' },
  { code: 'da', label: 'Danish',         nativeLabel: 'Dansk',         flag: '🇩🇰' },
  { code: 'no', label: 'Norwegian',      nativeLabel: 'Norsk',         flag: '🇳🇴' },
  { code: 'fi', label: 'Finnish',        nativeLabel: 'Suomi',         flag: '🇫🇮' },
  { code: 'el', label: 'Greek',          nativeLabel: 'Ελληνικά',      flag: '🇬🇷' },
  { code: 'cs', label: 'Czech',          nativeLabel: 'Čeština',       flag: '🇨🇿' },
  { code: 'ro', label: 'Romanian',       nativeLabel: 'Română',       flag: '🇷🇴' },
  { code: 'hu', label: 'Hungarian',      nativeLabel: 'Magyar',        flag: '🇭🇺' },
  { code: 'th', label: 'Thai',           nativeLabel: 'ไทย',            flag: '🇹🇭' },
  { code: 'vi', label: 'Vietnamese',     nativeLabel: 'Tiếng Việt',    flag: '🇻🇳' },
];

/* ================================================================
   Translation Dictionary — keyed by language code
   All text uses real UTF-8 characters; NO unicode escape sequences.
   ================================================================ */
interface Translations {
  switchLanguage: string;
  add: string;
  bestSeller: string;
  openToday: string;
  noDishes: string;
  menuNotFound: string;
  menuNotFoundDesc: string;
  goToHomepage: string;
  itemsInCart: string;
  yourOrder: string;
  yourCartIsEmpty: string;
  total: string;
  subtotal: string;
  taxService: string;
  placeOrder: string;
  newOrder: string;
  done: string;
  print: string;
  orderSlip: string;
  item: string;
  qty: string;
  price: string;
  each: string;
  showReceiptToServer: string;
  showReceiptToServerStrong: string;
  orderedVia: string;
  addToOrder: string;
  dietaryInfo: string;
  allergens: string;
  vegan: string;
  vegetarian: string;
  glutenFree: string;
  lactoseFree: string;
  dairyFree: string;
  spicy: string;
  hours: string;
  contact: string;
  followUs: string;
  /* Filter bar & bottom sheet */
  allergenFilter: string;
  dietaryFilter: string;
  allergenFilterTitle: string;
  allergenFilterDesc: string;
  dietaryFilterTitle: string;
  dietaryFilterDesc: string;
  noMatchingDishes: string;
  clearFilters: string;
  apply: string;
  /* Allergen names — used by tTag() for filter bottom sheet & dish detail */
  allergenGluten: string;
  allergenPeanuts: string;
  allergenEggs: string;
  allergenFish: string;
  allergenCrustaceans: string;
  allergenSoybeans: string;
  allergenMilk: string;
  allergenNuts: string;
  allergenCelery: string;
  allergenMustard: string;
  allergenSesame: string;
  allergenSulfites: string;
  allergenLupin: string;
  allergenMolluscs: string;
  /* Dish explanation popup */
  learningAboutDish: string;
  dishStory: string;
  aiInsights: string;
  tryAgain: string;
  gotIt: string;
}

const TRANSLATIONS: Record<string, Translations> = {
  en: {
    switchLanguage: 'Switch language',
    add: 'Add',
    bestSeller: 'Best seller',
    openToday: 'Open today · 11:00 AM – 10:30 PM',
    noDishes: 'No dishes in this section',
    menuNotFound: 'Menu not found',
    menuNotFoundDesc: 'The menu you are looking for does not exist or has been removed.',
    goToHomepage: 'Go to homepage',
    itemsInCart: '{0} item{1} in cart',
    yourOrder: 'Your Order',
    yourCartIsEmpty: 'Your cart is empty',
    total: 'Total',
    subtotal: 'Subtotal ({0} items)',
    taxService: 'Tax / Service',
    placeOrder: 'Place Order · Show Receipt',
    newOrder: 'New Order',
    done: 'Done',
    print: 'Print',
    orderSlip: 'Order Slip',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    each: '@{0} each',
    showReceiptToServer: '{0}They will process your order and bring you the final bill.',
    showReceiptToServerStrong: 'Show this receipt to your server.',
    orderedVia: 'Ordered via ',
    addToOrder: 'Add to Order',
    dietaryInfo: 'Dietary Info',
    allergens: 'Allergens',
    vegan: 'Vegan',
    vegetarian: 'Vegetarian',
    glutenFree: 'Gluten-free',
    lactoseFree: 'Lactose-free',
    dairyFree: 'Dairy-free',
    spicy: 'Spicy',
    hours: 'Hours',
    contact: 'Contact',
    followUs: 'Follow us',
    allergenFilter: 'Allergens',
    dietaryFilter: 'Dietary',
    allergenFilterTitle: 'Select your allergens',
    allergenFilterDesc: 'Dishes containing selected allergens will be hidden from the menu.',
    dietaryFilterTitle: 'Select dietary preferences',
    dietaryFilterDesc: 'Only dishes matching your preferences will be shown.',
    noMatchingDishes: 'No dishes match your filters',
    clearFilters: 'Clear all',
    apply: 'Apply',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Peanuts',
    allergenEggs: 'Eggs',
    allergenFish: 'Fish',
    allergenCrustaceans: 'Crustaceans',
    allergenSoybeans: 'Soybeans',
    allergenMilk: 'Milk',
    allergenNuts: 'Nuts',
    allergenCelery: 'Celery',
    allergenMustard: 'Mustard',
    allergenSesame: 'Sesame',
    allergenSulfites: 'Sulfites',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Molluscs',
    learningAboutDish: 'Learning about this dish...',
    dishStory: 'Dish Story',
    aiInsights: 'AI-powered cultural insights',
    tryAgain: 'Try again',
    gotIt: 'Got it!',
  },
  zh: {
    switchLanguage: '切换语言',
    add: '加入',
    bestSeller: '招牌推荐',
    openToday: '今日营业 · 11:00 – 22:30',
    noDishes: '该分类暂无菜品',
    menuNotFound: '菜单未找到',
    menuNotFoundDesc: '您查找的菜单不存在或已被移除。',
    goToHomepage: '返回首页',
    itemsInCart: '购物车共 {0} 件商品',
    yourOrder: '您的订单',
    yourCartIsEmpty: '购物车是空的',
    total: '合计',
    subtotal: '小计（{0} 件）',
    taxService: '税费 / 服务费',
    placeOrder: '确认下单 · 查看小票',
    newOrder: '新订单',
    done: '完成',
    print: '打印',
    orderSlip: '点餐单',
    item: '菜品',
    qty: '数量',
    price: '价格',
    each: '单价 @{0}',
    showReceiptToServer: '{0}服务员将为您处理订单并送来最终账单。',
    showReceiptToServerStrong: '请将此小票出示给服务员。',
    orderedVia: '通过 ',
    addToOrder: '加入订单',
    dietaryInfo: '饮食信息',
    allergens: '过敏原',
    vegan: '纯素',
    vegetarian: '素食',
    glutenFree: '无麸质',
    lactoseFree: '无乳糖',
    dairyFree: '无奶制品',
    spicy: '辣味',
    hours: '营业时间',
    contact: '联系方式',
    followUs: '关注我们',
    allergenFilter: '过敏原',
    dietaryFilter: '饮食偏好',
    allergenFilterTitle: '选择你的过敏原',
    allergenFilterDesc: '含有选中过敏原的菜品将从菜单中隐藏。',
    dietaryFilterTitle: '选择饮食偏好',
    dietaryFilterDesc: '只显示符合你偏好的菜品。',
    noMatchingDishes: '没有符合筛选条件的菜品',
    clearFilters: '清除筛选',
    apply: '应用',
    allergenGluten: '麸质',
    allergenPeanuts: '花生',
    allergenEggs: '鸡蛋',
    allergenFish: '鱼类',
    allergenCrustaceans: '甲壳类',
    allergenSoybeans: '大豆',
    allergenMilk: '牛奶',
    allergenNuts: '坚果',
    allergenCelery: '芹菜',
    allergenMustard: '芥末',
    allergenSesame: '芝麻',
    allergenSulfites: '亚硫酸盐',
    allergenLupin: '羽扇豆',
    allergenMolluscs: '软体动物',
    learningAboutDish: '正在了解这道菜...',
    dishStory: '菜品故事',
    aiInsights: 'AI 文化解读',
    tryAgain: '重试',
    gotIt: '知道了！',
  },
  es: {
    switchLanguage: 'Cambiar idioma',
    add: 'Añadir',
    bestSeller: 'Más vendido',
    openToday: 'Abierto hoy · 11:00 – 22:30',
    noDishes: 'No hay platos en esta sección',
    menuNotFound: 'Menú no encontrado',
    menuNotFoundDesc: 'El menú que busca no existe o ha sido eliminado.',
    goToHomepage: 'Ir al inicio',
    itemsInCart: '{0} artículo{1} en el carrito',
    yourOrder: 'Tu pedido',
    yourCartIsEmpty: 'Tu carrito está vacío',
    total: 'Total',
    subtotal: 'Subtotal ({0} artículos)',
    taxService: 'Impuestos / Servicio',
    placeOrder: 'Hacer pedido · Ver comprobante',
    newOrder: 'Nuevo pedido',
    done: 'Listo',
    print: 'Imprimir',
    orderSlip: 'Comanda',
    item: 'Artículo',
    qty: 'Cant.',
    price: 'Precio',
    each: '@{0} c/u',
    showReceiptToServer: '{0}Procesarán tu orden y te traerán la cuenta final.',
    showReceiptToServerStrong: 'Muestra este comprobante al mesero.',
    orderedVia: 'Pedido mediante ',
    addToOrder: 'Añadir al pedido',
    dietaryInfo: 'Información dietética',
    allergens: 'Alérgenos',
    vegan: 'Vegano',
    vegetarian: 'Vegetariano',
    glutenFree: 'Sin gluten',
    lactoseFree: 'Sin lactosa',
    dairyFree: 'Sin lácteos',
    spicy: 'Picante',
    hours: 'Horario',
    contact: 'Contacto',
    followUs: 'Síguenos',
    allergenFilter: 'Alérgenos',
    dietaryFilter: 'Dieta',
    allergenFilterTitle: 'Selecciona tus alérgenos',
    allergenFilterDesc: 'Los platos que contengan los alérgenos seleccionados se ocultarán del menú.',
    dietaryFilterTitle: 'Selecciona preferencias dietéticas',
    dietaryFilterDesc: 'Solo se mostrarán platos que coincidan con tus preferencias.',
    noMatchingDishes: 'Ningún plato coincide con los filtros',
    clearFilters: 'Limpiar todo',
    apply: 'Aplicar',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Cacahuates',
    allergenEggs: 'Huevos',
    allergenFish: 'Pescado',
    allergenCrustaceans: 'Crustáceos',
    allergenSoybeans: 'Soja',
    allergenMilk: 'Leche',
    allergenNuts: 'Frutos secos',
    allergenCelery: 'Apio',
    allergenMostaza: 'Mostaza',
    allergenSesame: 'Sésamo',
    allergenSulfites: 'Sulfitos',
    allergenLupin: 'Altramuces',
    allergenMolluscs: 'Moluscos',
  },
  fr: {
    switchLanguage: "Changer la langue",
    add: 'Ajouter',
    bestSeller: 'Best-seller',
    openToday: "Ouvert aujourd'hui · 11 h 00 – 22 h 30",
    noDishes: 'Aucun plat dans cette section',
    menuNotFound: 'Menu introuvable',
    menuNotFoundDesc: "Le menu que vous recherchez n'existe pas ou a été supprimé.",
    goToHomepage: "Aller à l'accueil",
    itemsInCart: "{0} article{1} dans le panier",
    yourOrder: 'Votre commande',
    yourCartIsEmpty: 'Votre panier est vide',
    total: 'Total',
    subtotal: 'Sous-total ({0} articles)',
    taxService: 'Taxes / Service',
    placeOrder: 'Passer commande · Voir reçu',
    newOrder: 'Nouvelle commande',
    done: 'Terminé',
    print: 'Imprimer',
    orderSlip: 'Bon de commande',
    item: 'Article',
    qty: 'Qté',
    price: 'Prix',
    each: "@{0} l'unité",
    showReceiptToServer: '{0}Ils traiteront votre commande et vous apporteront l addition finale.',
    showReceiptToServerStrong: 'Présentez ce reçu au serveur.',
    orderedVia: 'Commandé via ',
    addToOrder: 'Ajouter à la commande',
    dietaryInfo: 'Infos diététiques',
    allergens: 'Allergènes',
    vegan: 'Vegan',
    vegetarian: 'Végétarien',
    glutenFree: 'Sans gluten',
    lactoseFree: 'Sans lactose',
    dairyFree: 'Sans produits laitiers',
    spicy: 'Épicé',
    hours: "Horaires",
    contact: 'Contact',
    followUs: 'Suivez-nous',
    allergenFilter: 'Allergènes',
    dietaryFilter: 'Régime',
    allergenFilterTitle: 'Sélectionnez vos allergènes',
    allergenFilterDesc: 'Les plats contenant les allergènes sélectionnés seront masqués.',
    dietaryFilterTitle: 'Sélectionnez vos préférences alimentaires',
    dietaryFilterDesc: 'Seuls les plats correspondant à vos préférences seront affichés.',
    noMatchingDishes: 'Aucun plat ne correspond à vos filtres',
    clearFilters: 'Tout effacer',
    apply: 'Appliquer',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Arachides',
    allergenEggs: 'Oeufs',
    allergenFish: 'Poisson',
    allergenCrustaceans: 'Crustacés',
    allergenSoybeans: 'Soja',
    allergenMilk: 'Lait',
    allergenNuts: 'Fruits à coque',
    allergenCelery: 'Céleri',
    allergenMustard: 'Moutarde',
    allergenSesame: 'Sésame',
    allergenSulfites: 'Sulfites',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Mollusques',
    learningAboutDish: 'Découverte du plat...',
    dishStory: 'Histoire du plat',
    aiInsights: 'Anecdotes culturelles par IA',
    tryAgain: 'Réessayer',
    gotIt: 'Compris !',
  },
  de: {
    switchLanguage: 'Sprache wechseln',
    add: 'Hinzufügen',
    bestSeller: 'Beliebtestes Gericht',
    openToday: 'Heute geöffnet · 11:00 – 22:30 Uhr',
    noDishes: 'Keine Gerichte in dieser Kategorie',
    menuNotFound: 'Menü nicht gefunden',
    menuNotFoundDesc: 'Das gesuchte Menü existiert nicht oder wurde entfernt.',
    goToHomepage: 'Zur Startseite',
    itemsInCart: '{0} Artikel{1} im Warenkorb',
    yourOrder: 'Ihre Bestellung',
    yourCartIsEmpty: 'Ihr Warenkorb ist leer',
    total: 'Gesamt',
    subtotal: 'Zwischensumme ({0} Artikel)',
    taxService: 'Steuer / Service',
    placeOrder: 'Bestellung aufgeben · Quittung anzeigen',
    newOrder: 'Neue Bestellung',
    done: 'Fertig',
    print: 'Drucken',
    orderSlip: 'Bestellschein',
    item: 'Artikel',
    qty: 'Anz.',
    price: 'Preis',
    each: '@{0} pro Stk.',
    showReceiptToServer: '{0}Sie bearbeiten Ihre Bestellung und bringen Ihnen die Endrechnung.',
    showReceiptToServerStrong: 'Zeigen Sie diese Quittung dem Kellner.',
    orderedVia: 'Bestellt über ',
    addToOrder: 'Zur Bestellung hinzufügen',
    dietaryInfo: 'Diätetische Infos',
    allergens: 'Allergene',
    vegan: 'Vegan',
    vegetarian: 'Vegetarisch',
    glutenFree: 'Glutenfrei',
    lactoseFree: 'Laktosefrei',
    dairyFree: 'Milchfrei',
    spicy: 'Scharf',
    allergenFilter: 'Allergene',
    dietaryFilter: 'Ernährung',
    allergenFilterTitle: 'Wählen Sie Ihre Allergene',
    allergenFilterDesc: 'Gerichte mit ausgewählten Allergenen werden ausgeblendet.',
    dietaryFilterTitle: 'Ernährungsvorlieben wählen',
    dietaryFilterDesc: 'Es werden nur Gerichte angezeigt, die Ihren Vorlieben entsprechen.',
    noMatchingDishes: 'Keine Gerichte entsprechen den Filtern',
    clearFilters: 'Zurücksetzen',
    apply: 'Anwenden',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Erdnüsse',
    allergenEggs: 'Eier',
    allergenFish: 'Fisch',
    allergenCrustaceans: 'Krebstiere',
    allergenSoybeans: 'Sojabohnen',
    allergenMilk: 'Milch',
    allergenNuts: 'Schalenfrüchte',
    allergenCelery: 'Sellerie',
    allergenMustard: 'Senf',
    allergenSesame: 'Sesam',
    allergenSulfites: 'Sulfite',
    allergenLupin: 'Lupinen',
    allergenMolluscs: 'Weichtiere',
    learningAboutDish: 'Erkunde dieses Gericht...',
    dishStory: 'Geschichte des Gerichts',
    aiInsights: 'KI-Kultureinblicke',
    tryAgain: 'Erneut versuchen',
    gotIt: 'Verstanden!',
  },
  it: {
    switchLanguage: 'Cambia lingua',
    add: 'Aggiungi',
    bestSeller: 'Più venduto',
    openToday: 'Aperto oggi · 11:00 – 22:30',
    noDishes: 'Nessun piatto in questa sezione',
    menuNotFound: 'Menu non trovato',
    menuNotFoundDesc: 'Il menu che stai cercando non esiste o è stato rimosso.',
    goToHomepage: 'Vai alla home',
    itemsInCart: '{0} articolo{1} nel carrello',
    yourOrder: 'Il tuo ordine',
    yourCartIsEmpty: 'Il carrello è vuoto',
    total: 'Totale',
    subtotal: 'Subtotale ({0} articoli)',
    taxService: 'Tasse / Servizio',
    placeOrder: 'Effettua ordine · Mostra scontrino',
    newOrder: 'Nuovo ordine',
    done: 'Fatto',
    print: 'Stampa',
    orderSlip: 'Scontrino ordine',
    item: 'Articolo',
    qty: 'Qty',
    price: 'Prezzo',
    each: '@{0} cad.',
    showReceiptToServer: '{0}Elaboreranno il tuo ordine e ti porteranno il conto finale.',
    showReceiptToServerStrong: 'Mostra questo scontrino al cameriere.',
    orderedVia: 'Ordinato tramite ',
    addToOrder: "Aggiungi all'ordine",
    dietaryInfo: 'Info dietetiche',
    allergens: 'Allergeni',
    vegan: 'Vegano',
    vegetarian: 'Vegetariano',
    glutenFree: 'Senza glutine',
    lactoseFree: 'Senza lattosio',
    dairyFree: 'Senza latticini',
    spicy: 'Piccante',
    allergenFilter: 'Allergeni',
    dietaryFilter: 'Dieta',
    allergenFilterTitle: 'Seleziona i tuoi allergeni',
    allergenFilterDesc: 'I piatti contenenti gli allergeni selezionati saranno nascosti.',
    dietaryFilterTitle: 'Seleziona preferenze alimentari',
    dietaryFilterDesc: 'Verranno mostrati solo i piatti corrispondenti alle tue preferenze.',
    noMatchingDishes: 'Nessun piatto corrisponde ai filtri',
    clearFilters: 'Cancella tutto',
    apply: 'Applica',
    allergenGluten: 'Glutine',
    allergenPeanuts: 'Arachidi',
    allergenEggs: 'Uova',
    allergenFish: 'Pesce',
    allergenCrustaceans: 'Crostacei',
    allergenSoybeans: 'Soia',
    allergenMilk: 'Latte',
    allergenNuts: 'Frutta a guscio',
    allergenCelery: 'Sedano',
    allergenMustard: 'Senape',
    allergenSesame: 'Sesamo',
    allergenSulfites: 'Solfiti',
    allergenLupin: 'Lupini',
    allergenMolluscs: 'Molluschi',
    learningAboutDish: 'Alla scoperta di questo piatto...',
    dishStory: 'Storia del piatto',
    aiInsights: 'Approfondimenti culturali AI',
    tryAgain: 'Riprova',
    gotIt: 'Capito!',
  },
  pt: {
    switchLanguage: 'Mudar idioma',
    add: 'Adicionar',
    bestSeller: 'Mais vendido',
    openToday: 'Aberto hoje · 11:00 – 22:30',
    noDishes: 'Nenhum prato nesta seção',
    menuNotFound: 'Cardápio não encontrado',
    menuNotFoundDesc: 'O cardápio que você procura não existe ou foi removido.',
    goToHomepage: 'Ir para o início',
    itemsInCart: '{0} item{1} no carrinho',
    yourOrder: 'Seu pedido',
    yourCartIsEmpty: 'Seu carrinho está vazio',
    total: 'Total',
    subtotal: 'Subtotal ({0} itens)',
    taxService: 'Imposto / Serviço',
    placeOrder: 'Fazer pedido · Ver comprovante',
    newOrder: 'Novo pedido',
    done: 'Pronto',
    print: 'Imprimir',
    orderSlip: 'Comprovante',
    item: 'Item',
    qty: 'Qtd',
    price: 'Preço',
    each: '@{0} cada',
    showReceiptToServer: '{0}Eles processarão seu pedido e trarão a conta final.',
    showReceiptToServerStrong: 'Mostre este comprovante ao garçom.',
    orderedVia: 'Pedido via ',
    addToOrder: 'Adicionar ao pedido',
    dietaryInfo: 'Informação dietética',
    allergens: 'Alérgenos',
    vegan: 'Vegano',
    vegetarian: 'Vegetariano',
    glutenFree: 'Sem glúten',
    lactoseFree: 'Sem lactose',
    dairyFree: 'Sem laticínios',
    spicy: 'Picante',
    allergenFilter: 'Alérgenos',
    dietaryFilter: 'Dieta',
    allergenFilterTitle: 'Selecione seus alérgenos',
    allergenFilterDesc: 'Pratos com alérgenos selecionados serão ocultados.',
    dietaryFilterTitle: 'Selecione preferências dietéticas',
    dietaryFilterDesc: 'Apenas pratos que correspondem às suas preferências serão mostrados.',
    noMatchingDishes: 'Nenhum prato corresponde aos filtros',
    clearFilters: 'Limpar tudo',
    apply: 'Aplicar',
    allergenGluten: 'Glúten',
    allergenPeanuts: 'Amendoim',
    allergenEggs: 'Ovos',
    allergenFish: 'Peixe',
    allergenCrustaceans: 'Crustáceos',
    allergenSoybeans: 'Soja',
    allergenMilk: 'Leite',
    allergenNuts: 'Frutos secos',
    allergenCelery: 'Aipo',
    allergenMustard: 'Mostarda',
    allergenSesame: 'Gergelim',
    allergenSulfites: 'Sulfitos',
    allergenLupin: 'Tremoço',
    allergenMolluscs: 'Moluscos',
    learningAboutDish: 'Aprendendo sobre este prato...',
    dishStory: 'História do prato',
    aiInsights: 'Insights culturais com IA',
    tryAgain: 'Tentar novamente',
    gotIt: 'Entendi!',
  },
  nl: {
    switchLanguage: 'Taal wijzigen',
    add: 'Toevoegen',
    bestSeller: 'Bestseller',
    openToday: 'Vandaag geopend · 11:00 – 22:30',
    noDishes: 'Geen gerechten in deze sectie',
    menuNotFound: 'Menu niet gevonden',
    menuNotFoundDesc: 'Het menu dat u zoekt bestaat niet of is verwijderd.',
    goToHomepage: 'Naar homepagina',
    itemsInCart: '{0} artikel{1} in winkelwagen',
    yourOrder: 'Uw bestelling',
    yourCartIsEmpty: 'Uw winkelwagen is leeg',
    total: 'Totaal',
    subtotal: 'Subtotaal ({0} artikelen)',
    taxService: 'Belasting / Service',
    placeOrder: 'Bestelling plaatsen · Bon tonen',
    newOrder: 'Nieuwe bestelling',
    done: 'Klaar',
    print: 'Afdrukken',
    orderSlip: 'Bestelbon',
    item: 'Artikel',
    qty: 'Aantal',
    price: 'Prijs',
    each: '@{0} per stuk',
    showReceiptToServer: '{0}Zij verwerken uw bestelling en brengen de eindrekening.',
    showReceiptToServerStrong: 'Toon deze bon aan de ober.',
    orderedVia: 'Besteld via ',
    addToOrder: 'Toevoegen aan bestelling',
    dietaryInfo: 'Dieetinfo',
    allergens: 'Allergenen',
    vegan: 'Veganistisch',
    vegetarian: 'Vegetarisch',
    glutenFree: 'Glutenvrij',
    lactoseFree: 'Lactosevrij',
    dairyFree: 'Zuivelvrij',
    spicy: 'Pittig',
    allergenFilter: 'Allergenen',
    dietaryFilter: 'Dieet',
    allergenFilterTitle: 'Selecteer uw allergenen',
    allergenFilterDesc: 'Gerechten met geselecteerde allergenen worden verborgen.',
    dietaryFilterTitle: 'Selecteer dieetvoorkeuren',
    dietaryFilterDesc: 'Alleen gerechten die overeenkomen met uw voorkeuren worden weergegeven.',
    noMatchingDishes: 'Geen gerechten komen overeen met filters',
    clearFilters: 'Wis alles',
    apply: 'Toepassen',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Pinda\'s',
    allergenEggs: 'Eieren',
    allergenFish: 'Vis',
    allergenCrustaceans: 'Schaaldieren',
    allergenSoybeans: 'Soja',
    allergenMilk: 'Melk',
    allergenNuts: 'Noten',
    allergenCelery: 'Selderij',
    allergenMustard: 'Mosterd',
    allergenSesame: 'Sesamzaad',
    allergenSulfites: 'Sulfieten',
    allergenLupin: 'Lupine',
    allergenMolluscs: 'Weekdieren',
    learningAboutDish: 'Ontdek dit gerecht...',
    dishStory: 'Gerechtverhaal',
    aiInsights: 'AI culturele inzichten',
    tryAgain: 'Opnieuw proberen',
    gotIt: 'Begrepen!',
  },
  ru: {
    switchLanguage: 'Сменить язык',
    add: 'Добавить',
    bestSeller: 'Хит продаж',
    openToday: 'Открыто сегодня · 11:00 – 22:30',
    noDishes: 'В этой категории нет блюд',
    menuNotFound: 'Меню не найдено',
    menuNotFoundDesc: 'Искомое меню не существует или было удалено.',
    goToHomepage: 'На главную',
    itemsInCart: '{0} товар{1} в корзине',
    yourOrder: 'Ваш заказ',
    yourCartIsEmpty: 'Корзина пуста',
    total: 'Итого',
    subtotal: 'Промежуточный итог ({0} поз.)',
    taxService: 'Налоги / Обслуживание',
    placeOrder: 'Оформить · Показать чек',
    newOrder: 'Новый заказ',
    done: 'Готово',
    print: 'Печать',
    orderSlip: 'Чек заказа',
    item: 'Позиция',
    qty: 'Кол-во',
    price: 'Цена',
    each: '@{0} за шт.',
    showReceiptToServer: '{0}Официант обработает ваш заказ и принесёт итоговый счёт.',
    showReceiptToServerStrong: 'Покажите этот чек официанту.',
    orderedVia: 'Заказано через ',
    addToOrder: 'Добавить в заказ',
    dietaryInfo: 'Диетическая информация',
    allergens: 'Аллергены',
    vegan: 'Веганский',
    vegetarian: 'Вегетарианский',
    glutenFree: 'Без глютена',
    lactoseFree: 'Без лактозы',
    dairyFree: 'Без молочных продуктов',
    spicy: 'Острое',
    allergenFilter: 'Аллергены',
    dietaryFilter: 'Диета',
    allergenFilterTitle: 'Выберите ваши аллергены',
    allergenFilterDesc: 'Блюда с выбранными аллергенами будут скрыты.',
    dietaryFilterTitle: 'Выберите пищевые предпочтения',
    dietaryFilterDesc: 'Показывать только блюда, соответствующие вашим предпочтениям.',
    noMatchingDishes: 'Нет блюд, соответствующих фильтрам',
    clearFilters: 'Сбросить все',
    apply: 'Применить',
    allergenGluten: 'Глютен',
    allergenPeanuts: 'Арахис',
    allergenEggs: 'Яйца',
    allergenFish: 'Рыба',
    allergenCrustaceans: 'Ракообразные',
    allergenSoybeans: 'Соевые бобы',
    allergenMilk: 'Молоко',
    allergenNuts: 'Орехи',
    allergenCelery: 'Сельдерей',
    allergenMustard: 'Горчица',
    allergenSesame: 'Кунжут',
    allergenSulfites: 'Сульфиты',
    allergenLupin: 'Люпин',
    allergenMolluscs: 'Моллюски',
    learningAboutDish: 'Узнаём о блюде...',
    dishStory: 'История блюда',
    aiInsights: 'Культурные заметки от ИИ',
    tryAgain: 'Повторить',
    gotIt: 'Понятно!',
  },
  ja: {
    switchLanguage: '言語を変更',
    add: '追加',
    bestSeller: '人気No.1',
    openToday: '本日営業中 · 11:00 ～ 22:30',
    noDishes: 'このカテゴリには料理がありません',
    menuNotFound: 'メニューが見つかりません',
    menuNotFoundDesc: 'お探しのメニューは存在しないか、削除されました。',
    goToHomepage: 'ホームに戻る',
    itemsInCart: 'カートに{0}点',
    yourOrder: 'ご注文内容',
    yourCartIsEmpty: 'カートは空です',
    total: '合計',
    subtotal: '小計（{0}点）',
    taxService: '税金／サービス料',
    placeOrder: '注文する · レシート表示',
    newOrder: '新規注文',
    done: '完了',
    print: '印刷',
    orderSlip: '注文伝票',
    item: '商品名',
    qty: '数量',
    price: '価格',
    each: '@{0} /個',
    showReceiptToServer: '{0}スタッフがご注文を承り、最終のお会計をお持ちします。',
    showReceiptToServerStrong: 'このレシピートをスタッフにお見せください。',
    orderedVia: '注文元: ',
    addToOrder: '注文に追加',
    dietaryInfo: '食事制限情報',
    allergens: 'アレルゲン',
    vegan: 'ビーガン',
    vegetarian: 'ベジタリアン',
    glutenFree: 'グルテンフリー',
    lactoseFree: '乳糖不使用',
    dairyFree: '乳製品不使用',
    spicy: '辛い',
    hours: '営業時間',
    contact: 'お問い合わせ',
    followUs: 'フォローする',
    allergenFilter: 'アレルゲン',
    dietaryFilter: '食事制限',
    allergenFilterTitle: 'アレルゲンを選択',
    allergenFilterDesc: '選択したアレルゲンを含む料理は非表示になります。',
    dietaryFilterTitle: '食事の好みを選択',
    dietaryFilterDesc: 'あなたの好みに合った料理のみ表示されます。',
    noMatchingDishes: 'フィルターに一致する料理がありません',
    clearFilters: 'すべてクリア',
    apply: '適用',
    allergenGluten: 'グルテン',
    allergenPeanuts: 'ピーナッツ',
    allergenEggs: '卵',
    allergenFish: '魚類',
    allergenCrustaceans: '甲殻類',
    allergenSoybeans: '大豆',
    allergenMilk: '乳',
    allergenNuts: 'ナッツ類',
    allergenCelery: 'セロリ',
    allergenMustard: 'からし',
    allergenSesame: 'ごま',
    allergenSulfites: '亜硫酸塩',
    allergenLupin: 'ルパン',
    allergenMolluscs: '軟体動物',
    learningAboutDish: 'この料理について学習中...',
    dishStory: '料理の物語',
    aiInsights: 'AI 文化解説',
    tryAgain: '再試行',
    gotIt: '了解！',
  },
  ko: {
    switchLanguage: '언어 변경',
    add: '담기',
    bestSeller: '인기 메뉴',
    openToday: '영업 중 · 11:00 – 22:30',
    noDishes: '이 카테고리에 메뉴가 없습니다',
    menuNotFound: '메뉴를 찾을 수 없습니다',
    menuNotFoundDesc: '찾으시는 메뉴는 존재하지 않거나 삭제되었습니다.',
    goToHomepage: '홈으로 가기',
    itemsInCart: '장바구니 {0}개',
    yourOrder: '주문 내역',
    yourCartIsEmpty: '장바구니가 비어 있습니다',
    total: '합계',
    subtotal: '소계 ({0}개)',
    taxService: '세금 / 서비스료',
    placeOrder: '주문하기 · 영수증 보기',
    newOrder: '새 주문',
    done: '완료',
    print: '인쇄',
    orderSlip: '주문 전표',
    item: '메뉴',
    qty: '수량',
    price: '가격',
    each: '@{0} /개',
    showReceiptToServer: '{0}직원이 주문을 처리하고 최종 계산서를 가져다 드립니다.',
    showReceiptToServerStrong: '이 영수증을 직원에게 보여주세요.',
    orderedVia: '주문 경로: ',
    addToOrder: '주문에 추가',
    dietaryInfo: '식이 정보',
    allergens: '알레르기 유발 성분',
    vegan: '비건',
    vegetarian: '베지테리언',
    glutenFree: '글루텐 프리',
    lactoseFree: '락토스 프리',
    dairyFree: '유제품 무첨가',
    spicy: '매운맛',
    hours: '영업시간',
    contact: '연락처',
    followUs: '팔로우',
    allergenFilter: '알레르기',
    dietaryFilter: '식단',
    allergenFilterTitle: '알레르기 유발 성분 선택',
    allergenFilterDesc: '선택한 알레르기 성분이 포함된 메뉴는 숨겨집니다.',
    dietaryFilterTitle: '식습관 선호 선택',
    dietaryFilterDesc: '선호하는 메뉴만 표시됩니다.',
    noMatchingDishes: '필터와 일치하는 메뉴가 없습니다',
    clearFilters: '모두 지우기',
    apply: '적용',
    allergenGluten: '글루텐',
    allergenPeanuts: '땅콩',
    allergenEggs: '달걀',
    allergenFish: '생선류',
    allergenCrustaceans: '갑각류',
    allergenSoybeans: '대두',
    allergenMilk: '우유',
    allergenNuts: '견과류',
    allergenCelery: '셀러리',
    allergenMustard: '겨자',
    allergenSesame: '참깨',
    allergenSulfites: '아황산염',
    allergenLupin: '루핀',
    allergenMolluscs: '연체동물',
    learningAboutDish: '이 요리에 대해 알아보는 중...',
    dishStory: '요리 이야기',
    aiInsights: 'AI 문화 인사이트',
    tryAgain: '다시 시도',
    gotIt: '알겠습니다!',
  },
  ar: {
    switchLanguage: 'تغيير اللغة',
    add: 'إضافة',
    bestSeller: 'الأكثر مبيعاً',
    openToday: 'مفتوح اليوم · ١١:٠٠ ص – ٢٢:٣٠ م',
    noDishes: 'لا توجد أطباق في هذا القسم',
    menuNotFound: 'القائمة غير موجودة',
    menuNotFoundDesc: 'القائمة التي تبحث عنها غير موجودة أو تمت إزالتها.',
    goToHomepage: 'الذهاب للصفحة الرئيسية',
    itemsInCart: '{0} عنصر{1} في السلة',
    yourOrder: 'طلبك',
    yourCartIsEmpty: 'سلتك فارغة',
    total: 'المجموع',
    subtotal: 'المجموع الفرعي ({0} عناصر)',
    taxService: 'الضريبة / الخدمة',
    placeOrder: 'تقديم الطلب · عرض الإيصال',
    newOrder: 'طلب جديد',
    done: 'تم',
    print: 'طباعة',
    orderSlip: 'إيصال الطلب',
    item: 'العنصر',
    qty: 'الكمية',
    price: 'السعر',
    each: '@{0} للوحدة',
    showReceiptToServer: '{0}سيقومون بمعالجة طلبك وإحضار الفاتورة النهائية.',
    showReceiptToServerStrong: 'أظهر هذا الإيصال للنادل.',
    orderedVia: 'تم الطلب عبر ',
    addToOrder: 'إضافة إلى الطلب',
    dietaryInfo: 'معلومات غذائية',
    allergens: 'مسببات الحساسية',
    vegan: 'نباتي صارم',
    vegetarian: 'نباتي',
    glutenFree: 'خالي من الغلوتين',
    lactoseFree: 'خالي من اللاكتوز',
    dairyFree: 'خالي من الألبان',
    spicy: 'حار',
    allergenFilter: 'مسببات الحساسية',
    dietaryFilter: 'النظام الغذائي',
    allergenFilterTitle: 'حدد مسببات الحساسية',
    allergenFilterDesc: 'سيتم إخفاء الأطباق التي تحتوي على مسببات الحساسية المختارة.',
    dietaryFilterTitle: 'اختر التفضيلات الغذائية',
    dietaryFilterDesc: 'سيتم عرض الأطباق التي تتوافق مع تفضيلاتك فقط.',
    noMatchingDishes: 'لا توجد أطباق تطابق الفلاتر',
    clearFilters: 'مسح الكل',
    apply: 'تطبيق',
    allergenGluten: 'الجلوتين',
    allergenPeanuts: 'الفول السوداني',
    allergenEggs: 'البيض',
    allergenFish: 'الأسماك',
    allergenCrustaceans: 'قشريات',
    allergenSoybeans: 'فول الصويا',
    allergenMilk: 'الحليب',
    allergenNuts: 'المكسرات',
    allergenCelery: 'الكرفس',
    allergenMustard: 'ال خردل',
    allergenSesame: 'السمسم',
    allergenSulfites: 'الكبريتات',
    allergenLupin: 'الترمس',
    allergenMolluscs: 'الرخويات',
    learningAboutDish: 'نتعرف على هذا الطبق...',
    dishStory: 'قصة الطبق',
    aiInsights: 'رؤى ثقافية بالذكاء الاصطناعي',
    tryAgain: 'حاول مرة أخرى',
    gotIt: 'فهمت!',
  },
  tr: {
    switchLanguage: 'Dil değiştir',
    add: 'Ekle',
    bestSeller: 'En çok satan',
    openToday: 'Bugün açık · 11:00 – 22:30',
    noDishes: 'Bu bölümde yemek yok',
    menuNotFound: 'Menü bulunamadı',
    menuNotFoundDesc: 'Ardınızdaki menü mevcut değil veya kaldırılmış.',
    goToHomepage: 'Ana sayfaya git',
    itemsInCart: '{0} ürün{1} sepetinizde',
    yourOrder: 'Siparişiniz',
    yourCartIsEmpty: 'Sepetiniz boş',
    total: 'Toplam',
    subtotal: 'Ara toplam ({0} ürün)',
    taxService: 'Vergi / Hizmet',
    placeOrder: 'Sipariş ver · Fişi göster',
    newOrder: 'Yeni sipariş',
    done: 'Tamam',
    print: 'Yazdır',
    orderSlip: 'Sipariş fişi',
    item: 'Ürün',
    qty: 'Adet',
    price: 'Fiyat',
    each: '@{0} adet başına',
    showReceiptToServer: '{0}Garson siparişinizi işleyecek ve son faturanızı getirecek.',
    showReceiptToServerStrong: 'Bu fişi garsona gösterin.',
    orderedVia: 'Sipariş verildi: ',
    addToOrder: 'Siparişe ekle',
    dietaryInfo: 'Diyet bilgisi',
    allergens: 'Alerjenler',
    vegan: 'Vegan',
    vegetarian: 'Vejeteryan',
    glutenFree: 'Glütensiz',
    lactoseFree: 'Laktozsuz',
    dairyFree: 'Sütsüz',
    spicy: 'Acılı',
    allergenFilter: 'Alerjenler',
    dietaryFilter: 'Diyet',
    allergenFilterTitle: 'Alerjenlerinizi seçin',
    allergenFilterDesc: 'Seçilen alerjenleri içeren yemekler gizlenecek.',
    dietaryFilterTitle: 'Diyet tercihlerinizi seçin',
    dietaryFilterDesc: 'Sadece tercihlerinize uygun yemekler gösterilecek.',
    noMatchingDishes: 'Filtrele eşleşen yemek yok',
    clearFilters: 'Temizle',
    apply: 'Uygula',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Fıstık',
    allergenEggs: 'Yumurta',
    allergenFish: 'Balık',
    allergenCrustaceans: 'Kabuklular',
    allergenSoybeans: 'Soya',
    allergenMilk: 'Süt',
    allergenNuts: 'Kuruyemiş',
    allergenCelery: 'Kereviz',
    allergenMustard: 'Hardal',
    allergenSesame: 'Susam',
    allergenSulfites: 'Sülfitle',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Yumuşakçalar',
    learningAboutDish: 'Bu yemeği keşfediyoruz...',
    dishStory: 'Yemek Hikayesi',
    aiInsights: 'AI kültürel bilgiler',
    tryAgain: 'Tekrar dene',
    gotIt: 'Anladım!',
  },
  pl: {
    switchLanguage: 'Zmień język',
    add: 'Dodaj',
    bestSeller: 'Bestseller',
    openToday: 'Otwarte dzisiaj · 11:00 – 22:30',
    noDishes: 'Brak dań w tej kategorii',
    menuNotFound: 'Menu nie znalezione',
    menuNotFoundDesc: 'Poszukiwane menu nie istnieje lub zostało usunięte.',
    goToHomepage: 'Strona główna',
    itemsInCart: '{0} pozycj{1} w koszyku',
    yourOrder: 'Twoje zamówienie',
    yourCartIsEmpty: 'Twój koszyk jest pusty',
    total: 'Razem',
    subtotal: 'Podsumowanie ({0} poz.)',
    taxService: 'Podatek / Obsługa',
    placeOrder: 'Złóż zamówienie · Pokaż rachunek',
    newOrder: 'Nowe zamówienie',
    done: 'Gotowe',
    print: 'Drukuj',
    orderSlip: 'Rachunek',
    item: 'Pozycja',
    qty: 'Ilość',
    price: 'Cena',
    each: '@{0} /szt.',
    showReceiptToServer: '{0}Kelner przyjmie zamówienie i przyniesie końcowy rachunek.',
    showReceiptToServerStrong: 'Pokaż ten rachunek kelnerowi.',
    orderedVia: 'Zamówione przez ',
    addToOrder: 'Dodaj do zamówienia',
    dietaryInfo: 'Informacje dietetyczne',
    allergens: 'Alergeny',
    vegan: 'Wegański',
    vegetarian: 'Wegetariański',
    glutenFree: 'Bez glutenu',
    lactoseFree: 'Bez laktozy',
    dairyFree: 'Bez nabiału',
    spicy: 'Ostre',
    allergenFilter: 'Alergeny',
    dietaryFilter: 'Dieta',
    allergenFilterTitle: 'Wybierz swoje alergeny',
    allergenFilterDesc: 'Dania zawierające wybrane alergeny będą ukryte.',
    dietaryFilterTitle: 'Wybierz preferencje żywieniowe',
    dietaryFilterDesc: 'Będą wyświetlane tylko dania zgodne z Twoimi preferencjami.',
    noMatchingDishes: 'Brak dań pasujących do filtrów',
    clearFilters: 'Wyczyść wszystko',
    apply: 'Zastosuj',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Orzechy ziemne',
    allergenEggs: 'Jajka',
    allergenFish: 'Ryby',
    allergenCrustaceans: 'Skorupiaki',
    allergenSoybeans: 'Soja',
    allergenMilk: 'Mleko',
    allergenNuts: 'Orzechy',
    allergenCelery: 'Seler',
    allergenMustard: 'Gorczyca',
    allergenSesame: 'Sezam',
    allergenSulfites: 'Siarczyny',
    allergenLupin: 'Łubin',
    allergenMolluscs: 'Mięczaki',
    learningAboutDish: 'Poznajemy to danie...',
    dishStory: 'Historia dania',
    aiInsights: 'AI — ciekawostki kulturowe',
    tryAgain: 'Spróbuj ponownie',
    gotIt: 'Rozumiem!',
  },
  sv: {
    switchLanguage: 'Ändra språk',
    add: 'Lägg till',
    bestSeller: 'Bäst säljare',
    openToday: 'Öppet idag · 11:00 – 22:30',
    noDishes: 'Inga rätter i detta avsnitt',
    menuNotFound: 'Menyn hittades inte',
    menuNotFoundDesc: 'Menyn du söker finns inte eller har tagits bort.',
    goToHomepage: 'Gå till startsidan',
    itemsInCart: '{0} vara{1} i varukorgen',
    yourOrder: 'Din beställning',
    yourCartIsEmpty: 'Din varukorg är tom',
    total: 'Totalt',
    subtotal: 'Delsumma ({0} varor)',
    taxService: 'Skatt / Service',
    placeOrder: 'Lägg beställning · Visa kvitto',
    newOrder: 'Ny beställning',
    done: 'Klar',
    print: 'Skriv ut',
    orderSlip: 'Orderkvitto',
    item: 'Vara',
    qty: 'Antal',
    price: 'pris',
    each: '@{0} /st',
    showReceiptToServer: '{0}De kommer att hantera din beställning och hämta den slutliga notan.',
    showReceiptToServerStrong: 'Visa detta kvitto för personalen.',
    orderedVia: 'Beställt via ',
    addToOrder: 'Lägg till i beställningen',
    dietaryInfo: 'Kostnadsinformation',
    allergens: 'Allergener',
    vegan: 'Vegan',
    vegetarian: 'Vegetarisk',
    glutenFree: 'Glutenfri',
    lactoseFree: 'Laktosfri',
    dairyFree: 'Mejerifri',
    spicy: 'Stark',
    allergenFilter: 'Allergener',
    dietaryFilter: 'Kost',
    allergenFilterTitle: 'Välj dina allergener',
    allergenFilterDesc: 'Rätter med valda allergener döljs.',
    dietaryFilterTitle: 'Välj kostpreferenser',
    dietaryFilterDesc: 'Endast rätter som matchar dina preferenser visas.',
    noMatchingDishes: 'Inga rätter matchar filtren',
    clearFilters: 'Rensa allt',
    apply: 'Tillämpa',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Jordnötter',
    allergenEggs: 'Ägg',
    allergenFish: 'Fisk',
    allergenCrustaceans: 'Kräftdjur',
    allergenSoybeans: 'Sojabönor',
    allergenMilk: 'Mjölk',
    allergenNuts: 'Nötter',
    allergenCelery: 'Selleri',
    allergenMustard: 'Senap',
    allergenSesame: 'Sesamfrön',
    allergenSulfites: 'Sulfit',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Blötdjur',
    learningAboutDish: 'Lär oss om denna rätt...',
    dishStory: 'Rättens historia',
    aiInsights: 'AI-kulturella insikter',
    tryAgain: 'Försök igen',
    gotIt: 'Uppfattat!',
  },
  da: {
    switchLanguage: 'Ændr sprog',
    add: 'Tilføj',
    bestSeller: 'Bedst sælgende',
    openToday: 'Åben i dag · 11:00 – 22:30',
    noDishes: 'Ingen retter i denne kategori',
    menuNotFound: 'Menu ikke fundet',
    menuNotFoundDesc: 'Den menu du søger findes ikke eller er blevet fjernet.',
    goToHomepage: 'Gå til forsiden',
    itemsInCart: '{0} vare{1} i indkøbskurven',
    yourOrder: 'Din ordre',
    yourCartIsEmpty: 'Din indkøbskurv er tom',
    total: 'I alt',
    subtotal: 'Subtotal ({0} varer)',
    taxService: 'Skat / Service',
    placeOrder: 'Afgiv ordre · Vis kvittering',
    newOrder: 'Ny ordre',
    done: 'Færdig',
    print: 'Udskriv',
    orderSlip: 'Ordrekvittering',
    item: 'Vare',
    qty: 'Antal',
    price: 'Pris',
    each: '@{0} pr. stk.',
    showReceiptToServer: '{0}De vil behandle din ordre og bringe dig den endelige regning.',
    showReceiptToServerStrong: 'Vis denne kvittering til tjeneren.',
    orderedVia: 'Bestilt via ',
    addToOrder: 'Tilføj til ordre',
    dietaryInfo: 'Kostinfo',
    allergens: 'Allergener',
    vegan: 'Vegan',
    vegetarian: 'Vegetarisk',
    glutenFree: 'Glutenfri',
    lactoseFree: 'Laktosefri',
    dairyFree: 'Mælkefri',
    spicy: 'Stærk',
    allergenFilter: 'Allergener',
    dietaryFilter: 'Kosthold',
    allergenFilterTitle: 'Velg dine allergener',
    allergenFilterDesc: 'Retter med valgte allergener skjules.',
    dietaryFilterTitle: 'Velg kostholdspreferanser',
    dietaryFilterDesc: 'Kun retter som matcher preferansene vises.',
    noMatchingDishes: 'Ingen retter matcher filterne',
    clearFilters: 'Tøm alt',
    apply: 'Bruk',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Jordnødder',
    allergenEggs: 'Æg',
    allergenFish: 'Fisk',
    allergenCrustaceans: 'Krebsdyr',
    allergenSoybeans: 'Sojabønner',
    allergenMilk: 'Mælk',
    allergenNuts: 'Nødder',
    allergenCelery: 'Selleri',
    allergenMustard: 'Sennep',
    allergenSesame: 'Sesam',
    allergenSulfites: 'Sulfit',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Bløddyr',
    learningAboutDish: 'Lærer om denne ret...',
    dishStory: 'Rettens historie',
    aiInsights: 'AI-kulturelle indsigter',
    tryAgain: 'Prøv igen',
    gotIt: 'Forstået!',
  },
  no: {
    switchLanguage: 'Bytt språk',
    add: 'Legg til',
    bestSeller: 'Bestselger',
    openToday: 'Åpent i dag · 11:00 – 22:30',
    noDishes: 'Ingen retter i denne seksjonen',
    menuNotFound: 'Meny ikke funnet',
    menuNotFoundDesc: 'Menyen du ser etter finnes ikke eller er fjernet.',
    goToHomepage: 'Gå til forsiden',
    itemsInCart: '{0} vare{1} i handlekurven',
    yourOrder: 'Din bestilling',
    yourCartIsEmpty: 'Handlekurven din er tom',
    total: 'Total',
    subtotal: 'Delsum ({0} varer)',
    taxService: 'Avgift / Service',
    placeOrder: 'Legg inn bestilling · Vis kvittering',
    newOrder: 'Ny bestilling',
    done: 'Ferdig',
    print: 'Skriv ut',
    orderSlip: 'Ordrekvittering',
    item: 'Vare',
    qty: 'Antall',
    price: 'Pris',
    each: '@{0} pr. stk.',
    showReceiptToServer: '{0}De vil behandle bestillingen din og bringe deg den endelige regningen.',
    showReceiptToServerStrong: 'Vis denne kvitteringen til betjeningen.',
    orderedVia: 'Bestilt via ',
    addToOrder: 'Legg til i bestillingen',
    dietaryInfo: 'Kostholdsinfo',
    allergens: 'Allergener',
    vegan: 'Vegan',
    vegetarian: 'Vegetarisk',
    glutenFree: 'Glutenfri',
    lactoseFree: 'Laktosefri',
    dairyFree: 'Melkefri',
    spicy: 'Sterk',
    allergenFilter: 'Allergener',
    dietaryFilter: 'Kosthold',
    allergenFilterTitle: 'Velg allergenerne dine',
    allergenFilterDesc: 'Retter med valgte allergener skjules.',
    dietaryFilterTitle: 'Velg kostholdspreferanser',
    dietaryFilterDesc: 'Kun retter som matcher vises.',
    noMatchingDishes: 'Ingen retter matcher filterne',
    clearFilters: 'Tøm alle',
    apply: 'Bruk',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Peanøtter',
    allergenEggs: 'Egg',
    allergenFish: 'Fisk',
    allergenCrustaceans: 'Skalldyr',
    allergenSoybeans: 'Soyabønner',
    allergenMilk: 'Melk',
    allergenNuts: 'Nøtter',
    allergenCelery: 'Selleri',
    allergenMustard: 'Sennep',
    allergenSesame: 'Sesam',
    allergenSulfites: 'Sulfit',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Bløtdyr',
    learningAboutDish: 'Lærer om denne retten...',
    dishStory: 'Rettens historie',
    aiInsights: 'AI-kulturell innsikt',
    tryAgain: 'Prøv igjen',
    gotIt: 'Skjønner!',
  },
  fi: {
    switchLanguage: 'Vaihda kieli',
    add: 'Lisää',
    bestSeller: 'Suosituin',
    openToday: 'Avoinna tänään · 11:00 – 22:30',
    noDishes: 'Ei ruokia tässä osiossa',
    menuNotFound: 'Valikkoa ei löytynyt',
    menuNotFoundDesc: 'Etsimääsi valikkoa ei ole tai se on poistettu.',
    goToHomepage: 'Etusivulle',
    itemsInCart: '{0} tuotetta{1} ostoskorissa',
    yourOrder: 'Tilauksesi',
    yourCartIsEmpty: 'Ostokorisi on tyhjä',
    total: 'Yhteensä',
    subtotal: 'Välisumma ({0} tuotetta)',
    taxService: 'Verot / Palvelu',
    placeOrder: 'Tee tilaus · Näytä kuitti',
    newOrder: 'Uusi tilaus',
    done: 'Valmis',
    print: 'Tulosta',
    orderSlip: 'Tilauskuitti',
    item: 'Tuote',
    qty: 'Määrä',
    price: 'Hinta',
    each: '@{0} /kpl',
    showReceiptToServer: '{0}Henkilökunta käsittelee tilauksesi ja tuo loppulaskun.',
    showReceiptToServerStrong: 'Näytä tämä kuitti henkilökunnalle.',
    orderedVia: 'Tilattu palvelun kautta ',
    addToOrder: 'Lisää tilaukseen',
    dietaryInfo: 'Ruokavaliotiedot',
    allergens: 'Allergeenit',
    vegan: 'Vegaani',
    vegetarian: 'Kasvissyöjä',
    glutenFree: 'Gluteeniton',
    lactoseFree: 'Laktoositon',
    dairyFree: 'Maidoton',
    spicy: 'Tulinen',
    allergenFilter: 'Allergeenit',
    dietaryFilter: 'Ruokavalio',
    allergenFilterTitle: 'Valitse allergeenis',
    allergenFilterDesc: 'Valittuja allergeeneja sisältävät ruoat piilotetaan.',
    dietaryFilterTitle: 'Valitse ruokatoiveet',
    dietaryFilterDesc: 'Näytetään vain toiveitasi vastaavat ruoat.',
    noMatchingDishes: 'Ei ruokia, jotka vastaavat suodattimia',
    clearFilters: 'Tyhjennä kaikki',
    apply: 'Käytä',
    allergenGluten: 'Gluteeni',
    allergenPeanuts: 'Maapähkinät',
    allergenEggs: 'Munat',
    allergenFish: 'Kala',
    allergenCrustaceans: 'Äyriäiset',
    allergenSoybeans: 'Soijapavut',
    allergenMilk: 'Maito',
    allergenNuts: 'Pähkinät',
    allergenCelery: 'Selleree',
    allergenMustard: 'Sinappi',
    allergenSesame: 'Sesami',
    allergenSulfites: 'Sulfiitti',
    allergenLupin: 'Lupiini',
    allergenMolluscs: 'Nilviäiset',
    learningAboutDish: 'Tutustutaan tähän ruokaan...',
    dishStory: 'Ruoan tarina',
    aiInsights: 'Tekoälyn kulttuurinäkemyksiä',
    tryAgain: 'Yritä uudelleen',
    gotIt: 'Selvä!',
  },
  el: {
    switchLanguage: 'Αλλαγή γλώσσας',
    add: 'Προσθήκη',
    bestSeller: 'Πιο δημοφιλές',
    openToday: 'Ανοιχτά σήμερα · 11:00 – 22:30',
    noDishes: 'Δεν υπάρχουν πιάτα σε αυτή την κατηγορία',
    menuNotFound: 'Το μενού δεν βρέθηκε',
    menuNotFoundDesc: 'Το μενού που αναζητάτε δεν υπάρχει ή έχει αφαιρεθεί.',
    goToHomepage: 'Πήγαινε στην αρχική',
    itemsInCart: '{0} αντικείμενα{1} στο καλάθι',
    yourOrder: 'Η παραγγελία σας',
    yourCartIsEmpty: 'Το καλάθι σας είναι άδειο',
    total: 'Σύνολο',
    subtotal: 'Μερικό σύνολο ({0} αντικείμενα)',
    taxService: 'Φόρος / Υπηρεσία',
    placeOrder: 'Καταχώρηση παραγγελίας · Εμφάνιση απόδειξης',
    newOrder: 'Νέα παραγγελία',
    done: 'Ολοκληρώθηκε',
    print: 'Εκτύπωση',
    orderSlip: 'Απόδειξη παραγγελίας',
    item: 'Αντικείμενο',
    qty: 'Ποσότητα',
    price: 'Τιμή',
    each: '@{0} ανά τεμ.',
    showReceiptToServer: '{0}Θα επεξεργαστούν την παραγγελία σας και θα φέρουν τον τελικό λογαριασμό.',
    showReceiptToServerStrong: 'Δείξτε αυτή την απόδειξη στον σερβιτόρο.',
    orderedVia: 'Παραγγελία μέσω ',
    addToOrder: 'Προσθήκη στην παραγγελία',
    dietaryInfo: 'Πληροφορίες διατροφής',
    allergens: 'Αλλεργιογόνα',
    vegan: 'Βεγκαν',
    vegetarian: 'Χορτοφάγος',
    glutenFree: 'Χωρίς γλουτένη',
    lactoseFree: 'Χωρίς λακτόζη',
    dairyFree: 'Χωρίς γαλακτοκομικά',
    spicy: 'Πικάντικο',
    allergenFilter: 'Αλλεργιογόνα',
    dietaryFilter: 'Δίαιτα',
    allergenFilterTitle: 'Επιλέξτε τα αλλεργιογόνα σας',
    allergenFilterDesc: 'Τα πιάτα με επιλεγμένα αλλεργιογόνα θα κρυφτούν.',
    dietaryFilterTitle: 'Επιλέξτε διατροφικές προτιμήσεις',
    dietaryFilterDesc: 'Θα εμφανιστούν μόνο πιάτα που ταιριάζουν με τις προτιμήσεις σας.',
    noMatchingDishes: 'Κανένα πιάτο δεν ταιριάζει με τα φίλτρα',
    clearFilters: 'Εκκαθάριση όλων',
    apply: 'Εφαρμογή',
    allergenGluten: 'Γλουτένη',
    allergenPeanuts: 'Φυστίκια',
    allergenEggs: 'Αυγά',
    allergenFish: 'Ψάρι',
    allergenCrustaceans: 'Δατυλόποδα',
    allergenSoybeans: 'Σόγια',
    allergenMilk: 'Γάλα',
    allergenNuts: 'Ξηροί καρποί',
    allergenCelery: 'Σέλερινο',
    allergenMustard: 'Μουστάρδα',
    allergenSesame: 'Σουσάμι',
    allergenSulfites: 'Θειώδη',
    allergenLupin: 'Λούπινο',
    allergenMolluscs: 'Μαλάκια',
    learningAboutDish: 'Μαθαίνοντας για αυτό το πιάτο...',
    dishStory: 'Ιστορία πιάτου',
    aiInsights: 'Πολιτιστικές πληροφορίες AI',
    tryAgain: 'Δοκιμάστε ξανά',
    gotIt: 'Το κατάλαβα!',
  },
  cs: {
    switchLanguage: 'Změnit jazyk',
    add: 'Přidat',
    bestSeller: 'Nejprodávanější',
    openToday: 'Otevřeno dnes · 11:00 – 22:30',
    noDishes: 'V této kategorii nejsou jídla',
    menuNotFound: 'Nabídka nenalezena',
    menuNotFoundDesc: 'Nabídka, kterou hledáte, neexistuje nebo byla odstraněna.',
    goToHomepage: 'Na úvodní stránku',
    itemsInCart: '{0} položek{1} v košíku',
    yourOrder: 'Vaše objednávka',
    yourCartIsEmpty: 'Váš košík je prázdný',
    total: 'Celkem',
    subtotal: 'Mezisoučet ({0} položek)',
    taxService: 'Daň / Služba',
    placeOrder: 'Objednat · Zobrazit účtenku',
    newOrder: 'Nová objednávka',
    done: 'Hotovo',
    print: 'Tisknout',
    orderSlip: 'Účtenka objednávky',
    item: 'Položka',
    qty: 'Počet',
    price: 'Cena',
    each: '@{0} /ks',
    showReceiptToServer: '{0}Personál zpracuje vaši objednávku a přinese konečný účet.',
    showReceiptToServerStrong: 'Ukažte tuto účtenku personálu.',
    orderedVia: 'Objednáno přes ',
    addToOrder: 'Přidat k objednávce',
    dietaryInfo: 'Dietní informace',
    allergens: 'Alergeny',
    vegan: 'Veganské',
    vegetarian: 'Vegetariánské',
    glutenFree: 'Bez lepku',
    lactoseFree: 'Bez laktózy',
    dairyFree: 'Bez mléčných výrobků',
    spicy: 'Pálivé',
    allergenFilter: 'Alergeny',
    dietaryFilter: 'Dieta',
    allergenFilterTitle: 'Vyberte své alergeny',
    allergenFilterDesc: 'Jídla s vybranými alergeny budou skryta.',
    dietaryFilterTitle: 'Vyberte dietní preference',
    dietaryFilterDesc: 'Zobrazí se pouze jídla odpovídající vašim preferencím.',
    noMatchingDishes: 'Žádná jídla neodpovídají filtrům',
    clearFilters: 'Vymazat vše',
    apply: 'Použít',
    allergenGluten: 'Lepek',
    allergenPeanuts: 'Arašídy',
    allergenEggs: 'Vejce',
    allergenFish: 'Ryby',
    allergenCrustaceans: 'Korýši',
    allergenSoybeans: 'Soya',
    allergenMilk: 'Mléko',
    allergenNuts: 'Ořechy',
    allergenCelery: 'Celer',
    allergenMustard: 'Hořčice',
    allergenSesame: 'Sézam',
    allergenSulfity: 'Sulfity',
    allergenLupin: 'Vikuł',
    allergenMolluscs: 'Měkkýši',
    learningAboutDish: 'Poznáváme tento pokrm...',
    dishStory: 'Příběh pokrmu',
    aiInsights: 'AI kulturní postřehy',
    tryAgain: 'Zkusit znovu',
    gotIt: 'Chápu!',
  },
  ro: {
    switchLanguage: 'Schimbă limba',
    add: 'Adaugă',
    bestSeller: 'Cel mai vândut',
    openToday: 'Deschis astăzi · 11:00 – 22:30',
    noDishes: 'Nu sunt preparate în această secțiune',
    menuNotFound: 'Meniu negăsit',
    menuNotFoundDesc: 'Meniul căutat nu există sau a fost eliminat.',
    goToHomepage: 'Pagina principală',
    itemsInCart: '{0} produs{1} în coș',
    yourOrder: 'Comanda ta',
    yourCartIsEmpty: 'Coșul tău este gol',
    total: 'Total',
    subtotal: 'Subtotal ({0} produse)',
    taxService: 'Taxe / Serviciu',
    placeOrder: 'Plasează comandă · Arată bonul',
    newOrder: 'Comandă nouă',
    done: 'Gata',
    print: 'Tipărește',
    orderSlip: 'Bon de comandă',
    item: 'Produs',
    qty: 'Cant.',
    price: 'Preț',
    each: '@{0} /buc.',
    showReceiptToServer: '{0}Personalul va procesa comanda și va aduce nota finală.',
    showReceiptToServerStrong: 'Arată acest bon chelnerului.',
    orderedVia: 'Comandat prin ',
    addToOrder: 'Adaugă la comandă',
    dietaryInfo: 'Informații dietetice',
    allergens: 'Alergeni',
    vegan: 'Vegan',
    vegetarian: 'Vegetarian',
    glutenFree: 'Fără gluten',
    lactoseFree: 'Fără lactoză',
    dairyFree: 'Fără lactate',
    spicy: 'Picant',
    allergenFilter: 'Alergeni',
    dietaryFilter: 'Dieta',
    allergenFilterTitle: 'Selectează alergenii tăi',
    allergenFilterDesc: 'Preparatele cu alergenii selectați vor fi ascunse.',
    dietaryFilterTitle: 'Selectează preferințe dietetice',
    dietaryFilterDesc: 'Vor fi afișate doar preparatele care corespund preferințelor tale.',
    noMatchingDishes: 'Niciun preparat nu se potrivește cu filtrele',
    clearFilters: 'Șterge totul',
    apply: 'Aplică',
    allergenGluten: 'Gluten',
    allergenPeanuts: 'Arahide',
    allergenEggs: 'Ouă',
    allergenFish: 'Pește',
    allergenCrustaceans: 'Crustacee',
    allergenSoybeans: 'Soia',
    allergenMilk: 'Lapte',
    allergenNuts: 'Nuci',
    allergenCelery: 'Țelină',
    allergenMustard: 'Muștar',
    allergenSesame: 'Seminte de susan',
    allergenSulfite: 'Sulfiți',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Moluste',
    learningAboutDish: 'Aflăm despre acest preparat...',
    dishStory: 'Povestea preparatului',
    aiInsights: 'Informații culturale AI',
    tryAgain: 'Încearcă din nou',
    gotIt: 'Am înțeles!',
  },
  hu: {
    switchLanguage: 'Nyelv váltása',
    add: 'Hozzáadás',
    bestSeller: 'Legnépszerűbb',
    openToday: 'Ma nyitva · 11:00 – 22:30',
    noDishes: 'Nincs étel ebben a kategóriában',
    menuNotFound: 'Menü nem található',
    menuNotFoundDesc: 'A keresett menü nem létezik vagy törölve lett.',
    goToHomepage: 'Főoldal',
    itemsInCart: '{0} termék{1} a kosárban',
    yourOrder: 'Megrendelésed',
    yourCartIsEmpty: 'A kosarad üres',
    total: 'Összesen',
    subtotal: 'Részösszeg ({0} termék)',
    taxService: 'Adó / Szolgáltatás',
    placeOrder: 'Megrendelés · Nyugta megtekintése',
    newOrder: 'Új rendelés',
    done: 'Kész',
    print: 'Nyomtatás',
    orderSlip: 'Rendelési nyugta',
    item: 'Termék',
    qty: 'Db.',
    price: 'Ár',
    each: '@{0} /db',
    showReceiptToServer: '{0}A személyzet feldolgozza a rendelésed és hozza a végszámlát.',
    showReceiptToServerStrong: 'Mutasd ezt a nyugtát a pincérnek.',
    orderedVia: 'Rendelve: ',
    addToOrder: 'Kosárba tesz',
    dietaryInfo: 'Diétás információk',
    allergens: 'Allergének',
    vegan: 'Vegán',
    vegetarian: 'Vegetáriánus',
    glutenFree: 'Glutenmentes',
    lactoseFree: 'Laktózmentes',
    dairyFree: 'Tejmentes',
    spicy: 'Csípős',
    allergenFilter: 'Allergének',
    dietaryFilter: 'Diéta',
    allergenFilterTitle: 'Válaszd ki az allergeneidet',
    allergenFilterDesc: 'A kiválasztott allergéneket tartalmazó ételek elrejtésre kerülnek.',
    dietaryFilterTitle: 'Étrendi preferenciák választása',
    dietaryFilterDesc: 'Csak a preferenciádnak megfelelő ételek jelennek meg.',
    noMatchingDishes: 'Nincs étel, ami megfelel a szűrőknek',
    clearFilters: 'Összes törlése',
    apply: 'Alkalmaz',
    allergenGluten: 'Glutén',
    allergenPeanuts: 'Földimogyoró',
    allergenEggs: 'Tojás',
    allergenFish: 'Hal',
    allergenCrustaceans: 'Rákok',
    allergenSoybeans: 'Szója',
    allergenMilk: 'Tej',
    allergenNuts: 'Diófélék',
    allergenCelery: 'Zeller',
    allergenMustard: 'Mustár',
    allergenSesame: 'Szezám',
    allergenSulfites: 'Szulfitok',
    allergenLupin: 'Lupin',
    allergenMolluscs: 'Puhatestűek',
    learningAboutDish: 'Ismerjük meg ezt az ételt...',
    dishStory: 'Az étel története',
    aiInsights: 'AI kulturális betekintés',
    tryAgain: 'Próbáld újra',
    gotIt: 'Értem!',
  },
  th: {
    switchLanguage: 'เปลี่ยนภาษา',
    add: 'เพิ่ม',
    bestSeller: 'ขายดีที่สุด',
    openToday: 'เปิดให้บริการวันนี้ · 11:00 – 22:30',
    noDishes: 'ไม่มีอาหารในหมวดนี้',
    menuNotFound: 'ไม่พบเมนู',
    menuNotFoundDesc: 'เมนูที่คุณกำลังค้นหาไม่มีอยู่หรือถูกลบออกแล้ว',
    goToHomepage: 'ไปหน้าแรก',
    itemsInCart: '{0} รายการ{1} ในตะกร้า',
    yourOrder: 'รายการสั่งซื้อของคุณ',
    yourCartIsEmpty: 'ตะกร้าของคุณว่างเปล่า',
    total: 'รวมทั้งสิ้น',
    subtotal: 'รวมย่อย ({0} รายการ)',
    taxService: 'ภาษี / ค่าบริการ',
    placeOrder: 'สั่งซื้อ · แสดงใบเสร็จ',
    newOrder: 'สั่งซื้อใหม่',
    done: 'เสร็จสิ้น',
    print: 'พิมพ์',
    orderSlip: 'ใบเสร็จสั่งซื้อ',
    item: 'รายการ',
    qty: 'จำนวน',
    price: 'ราคา',
    each: '@{0} /ชิ้น',
    showReceiptToServer: '{0}พนักงานจะดำเนินการคำสั่งซื้อและนำบิลสุดท้ายมาให้คุณ',
    showReceiptToServerStrong: 'แสดงใบเสร็จนี้ให้พนักงานดู',
    orderedVia: 'สั่งซื้อผ่าน ',
    addToOrder: 'เพิ่มลงในคำสั่งซื้อ',
    dietaryInfo: 'ข้อมูลอาหารพิเศษ',
    allergens: 'สารก่อภูมิแพ้',
    vegan: 'เวแกน',
    vegetarian: 'มังสวิรัติ',
    glutenFree: 'ปลอกลูเตน',
    lactoseFree: 'ปลอกลักโทส',
    dairyFree: 'ปลอกนม',
    spicy: 'เผ็ด',
    allergenFilter: 'สารก่อภูมิแพ้',
    dietaryFilter: 'อาหารเฉพาะ',
    allergenFilterTitle: 'เลือกสารที่คุณแพ้',
    allergenFilterDesc: 'อาหารที่มีสารก่อภูมิแพ้ที่เลือกจะถูกซ่อน',
    dietaryFilterTitle: 'เลือกความชอบด้านอาหาร',
    dietaryFilterDesc: 'แสดงเฉพาะอาหารที่ตรงกับความชอบของคุณเท่านั้น',
    noMatchingDishes: 'ไม่มีอาหารตรงตามตัวกรอง',
    clearFilters: 'ล้างข้อมูลทั้งหมด',
    apply: 'ใช้งาน',
    allergenGluten: 'กลูเตน',
    allergenPeanuts: 'ถั่วลันเตีย',
    allergenEggs: 'ไข่',
    allergenFish: 'ปลา',
    allergenCrustaceans: 'สัตว์เปลือกแข็ง',
    allergenSoybeans: 'ถั่วเหลือง',
    allergenMilk: 'นม',
    allergenNuts: 'ถั่ว / เมล็ดพืช',
    allergenCelery: 'คอรี่แฟงค์',
    allergenMustard: 'ผักกาดขาว',
    allergenSesame: 'งา',
    allergenSulfites: 'ซัลไฟต์',
    allergenLupin: 'ถัวลูปิน',
    allergenMolluscs: 'หอยสองเปลือก',
    learningAboutDish: 'กำลังเรียนรู้เกี่ยวกับเมนูนี้...',
    dishStory: 'เรื่องราวของเมนู',
    aiInsights: 'ข้อมูลเชิงวัฒนธรรมโดย AI',
    tryAgain: 'ลองอีกครั้ง',
    gotIt: 'เข้าใจแล้ว!',
  },
  vi: {
    switchLanguage: 'Đổi ngôn ngữ',
    add: 'Thêm',
    bestSeller: 'Bán chạy nhất',
    openToday: 'Mở cửa hôm nay · 11:00 – 22:30',
    noDishes: 'Không có món ăn trong mục này',
    menuNotFound: 'Không tìm thấy thực đơn',
    menuNotFoundDesc: 'Thực đơn bạn tìm không tồn tại hoặc đã bị xóa.',
    goToHomepage: 'Về trang chủ',
    itemsInCart: '{0} mặt hàng{1} trong giỏ',
    yourOrder: 'Đơn hàng của bạn',
    yourCartIsEmpty: 'Giỏ hàng của bạn trống',
    total: 'Tổng cộng',
    subtotal: 'Tạm tính ({0} mặt hàng)',
    taxService: 'Thuế / Phục vụ',
    placeOrder: 'Đặt hàng · Xem hóa đơn',
    newOrder: 'Đơn hàng mới',
    done: 'Hoàn tất',
    print: 'In',
    orderSlip: 'Biên lai đặt hàng',
    item: 'Mặt hàng',
    qty: 'SL',
    price: 'Giá',
    each: '@{0} /cái',
    showReceiptToServer: '{0}Nhân viên sẽ xử lý đơn hàng và mang hóa đơn cuối đến cho bạn.',
    showReceiptToServerStrong: 'Hiển thị biên lai này cho nhân viên phục vụ.',
    orderedVia: 'Đặt qua ',
    addToOrder: 'Thêm vào đơn hàng',
    dietaryInfo: 'Thông tin chế độ ăn',
    allergens: 'Dị ứng nguyên',
    vegan: 'Chay thuần chay',
    vegetarian: 'Ăn chay',
    glutenFree: 'Không gluten',
    lactoseFree: 'Không lactose',
    dairyFree: 'Không sữa',
    spicy: 'Cay',
    allergenFilter: 'Dị ứng nguyên',
    dietaryFilter: 'Chế độ ăn',
    allergenFilterTitle: 'Chọn dị ứng của bạn',
    allergenFilterDesc: 'Món ăn chứa dị ứng đã chọn sẽ bị ẩn.',
    dietaryFilterTitle: 'Chọn sở thích chế độ ăn',
    dietaryFilterDesc: 'Chỉ hiển thị món ăn phù hợp với sở thích của bạn.',
    noMatchingDishes: 'Không có món nào khớp với bộ lọc',
    clearFilters: 'Xóa bộ lọc',
    apply: 'Áp dụng',
    allergenGluten: ' Gluten',
    allergenPeanuts: 'Đậu phộng',
    allergenEggs: 'Trứng',
    allergenFish: 'Cá',
    allergenCrustaceans: 'Giáp xác',
    allergenSoybeans: 'Đậu nành',
    allergenMilk: 'Sữa',
    allergenNuts: 'Hạt có vỏ',
    allergenCelery: 'Cần tây',
    allergenMustard: 'Mù tạt',
    allergenSesame: 'Mè',
    allergenSulfites: 'Sunfit',
    allergenLupin: 'Đậu Lupin',
    allergenMolluscs: 'Động vật thân mềm',
    learningAboutDish: 'Đang tìm hiểu về món này...',
    dishStory: 'Câu chuyện món ăn',
    aiInsights: 'Thông tin văn hóa từ AI',
    tryAgain: 'Thử lại',
    gotIt: 'Đã hiểu!',
  },
};

/* Fallback for unsupported languages: use English */
function getTranslations(code: string): Translations {
  return TRANSLATIONS[code] || TRANSLATIONS['en']!;
}

/* ================================================================
   Section / Category name translations
   ================================================================ */
const SECTION_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {},
  zh: {
    'Starters': '开胃菜', 'Main Dishes': '主菜', 'Desserts': '甜点', 'Beverages': '饮品',
    'Salads': '沙拉', 'Soup': '汤品', 'Appetizers': '前菜', 'Entrees': '主菜',
    'Sides': '配菜', 'Specials': '特色菜', 'Amuse-Bouche': '餐前小点',
    'Pizza & Pasta': '披萨意面', 'Grill & BBQ': '烧烤', 'Seafood': '海鲜',
    'Vegetarian': '素食', 'Kids Menu': '儿童菜单', 'Breakfast': '早餐',
    'Lunch Specials': '午餐特惠', 'Dinner': '晚餐', 'Happy Hour': '欢乐时光',
    "Chef's Recommendations": '主厨推荐', 'Seasonal Specials': '季节限定',
    'Small Plates': '小盘菜', 'From the Kitchen': '厨房精选', 'From the Grill': '现烤系列',
  },
  ja: {
    'Starters': '前菜', 'Main Dishes': 'メイン料理', 'Desserts': 'デザート', 'Beverages': 'ドリンク',
    'Salads': 'サラダ', 'Soup': 'スープ', 'Appetizers': 'アペタイザー', 'Entrees': 'エントリー',
    'Sides': 'サイドディッシュ', 'Specials': 'スペシャル', 'Amuse-Bouche': 'アミューズブーシュ',
    'Pizza & Pasta': 'ピザ＆パスタ', 'Grill & BBQ': 'グリル＆BBQ', 'Seafood': 'シーフード',
    'Vegetarian': 'ベジタリアン', 'Kids Menu': 'キッズメニュー', 'Breakfast': '朝食',
    'Lunch Specials': 'ランチスペシャル', 'Dinner': 'ディナー', 'Happy Hour': 'ハッピーアワー',
    "Chef's Recommendations": "シェフのおすすめ", 'Seasonal Specials': '季節の限定品',
    'Small Plates': '小皿料理', 'From the Kitchen': 'キッチンから', 'From the Grill': 'グリル料理',
  },
  ko: {
    'Starters': '전체 요리', 'Main Dishes': '메인 요리', 'Desserts': '디저트', 'Beverages': '음료',
    'Salads': '샐러드', 'Soup': '스프', 'Appetizers': '애피타이저', 'Entrees': '엔트리',
    'Sides': '사이드', 'Specials': '스페셜', 'Amuse-Bouche': '아뮈즈 부슈',
    'Pizza & Pasta': '피자 & 파스타', 'Grill & BBQ': '그릴 & 바비큐', 'Seafood': '해산물',
    'Vegetarian': '채식', 'Kids Menu': '키즈 메뉴', 'Breakfast': '조식',
    'Lunch Specials': '런치 스페셜', 'Dinner': '디너', 'Happy Hour': '해피 아워',
    "Chef's Recommendations": '셰프 추천', 'Seasonal Specials': '시즌 스페셜',
    'Small Plates': '소플레이트', 'From the Kitchen': '키친 스페셜', 'From the Grill': '그릴 스페셜',
  },
  es: {
    'Starters': 'Entrantes', 'Main Dishes': 'Platos Principales', 'Desserts': 'Postres', 'Beverages': 'Bebidas',
    'Salads': 'Ensaladas', 'Soup': 'Sopas', 'Appetizers': 'Aperitivos', 'Entrees': 'Platos Fuertes',
    'Sides': 'Guarniciones', 'Specials': 'Especiales', 'Amuse-Bouche': 'Aperitivo del Chef',
    'Pizza & Pasta': 'Pizzas y Pastas', 'Grill & BBQ': 'Parrilla y BBQ', 'Seafood': 'Mariscos',
    'Vegetarian': 'Vegetariano', 'Kids Menu': 'Menú Infantil', 'Breakfast': 'Desayuno',
    'Lunch Specials': 'Menú del Día', 'Dinner': 'Cena', 'Happy Hour': 'Feliz Hora',
    "Chef's Recommendations": 'Recomendaciones del Chef', 'Seasonal Specials': 'Especialidades de Temporada',
    'Small Plates': 'Pet Platillos', 'From the Kitchen': 'De la Cocina', 'From the Grill': 'De la Parrilla',
  },
  fr: {
    'Starters': 'Entrées', 'Main Dishes': 'Plats Principaux', 'Desserts': 'Desserts', 'Beverages': 'Boissons',
    'Salads': 'Salades', 'Soup': 'Soupes', 'Appetizers': 'Apéritifs', 'Entrees': 'Plats',
    'Sides': 'Accompagnements', 'Specials': 'Spécialités', 'Amuse-Bouche': 'Amuse-bouche',
    'Pizza & Pasta': 'Pizzas et Pâtes', 'Grill & BBQ': 'Grillades', 'Seafood': 'Fruits de Mer',
    'Vegetarian': 'Végétarien', 'Kids Menu': 'Menu Enfants', 'Breakfast': 'Petit Déjeuner',
    'Lunch Specials': 'Menu du Midi', 'Dinner': 'Dîner', 'Happy Hour': "Heureux",
    "Chef's Recommendations": 'Suggestions du Chef', 'Seasonal Specials': 'Spécialités de Saison',
    'Small Plates': 'Petites Assiettes', 'From the Kitchen': 'De la Cuisine', 'From the Grill': 'Du Grill',
  },
  de: {
    'Starters': 'Vorspeisen', 'Main Dishes': 'Hauptgerichte', 'Desserts': 'Nachspeisen', 'Beverages': 'Getränke',
    'Salads': 'Salate', 'Soup': 'Suppen', 'Appetizers': 'Vorspeisen', 'Entrees': 'Hauptgänge',
    'Sides': 'Beilagen', 'Specials': 'Spezialitäten', 'Amuse-Bouche': 'Amuse-Gueule',
    'Pizza & Pasta': 'Pizza & Pasta', 'Grill & BBQ': 'Grill & BBQ', 'Seafood': 'Meeresfrüchte',
    'Vegetarian': 'Vegetarisch', 'Kids Menu': 'Kindermenü', 'Breakfast': 'Frühstück',
    'Lunch Specials': 'Mittagsmenü', 'Dinner': 'Abendessen', 'Happy Hour': 'Glückliche Stunde',
    "Chef's Recommendations": 'Empfehlung des Chefs', 'Seasonal Specials': 'Saisonale Spezialitäten',
    'Small Plates': 'Kleine Teller', 'From the Kitchen': 'Aus der Küche', 'From the Grill': 'Vom Grill',
  },
  it: {
    'Starters': 'Antipasti', 'Main Dishes': 'Piatti Principali', 'Desserts': 'Dolci', 'Beverages': 'Bevande',
    'Salads': 'Insalate', 'Soup': 'Zuppe', 'Appetizers': 'Antipasti', 'Entrees': 'Piatti Forti',
    'Sides': 'Contorni', 'Specials': 'Specialità', 'Amuse-Bouche': 'Amuse-bouche',
    'Pizza & Pasta': 'Pizza e Pasta', 'Grill & BBQ': 'Grigliata e BBQ', 'Seafood': 'Frutti di Mare',
    'Vegetarian': 'Vegetariano', 'Kids Menu': 'Menu Bambini', 'Breakfast': 'Colazione',
    'Lunch Specials': 'Menu del Giorno', 'Dinner': 'Cena', 'Happy Hour': 'Happy Hour',
    "Chef's Recommendations": 'Consigli dello Chef', 'Seasonal Specials': 'Specialità di Stagione',
    'Small Plates': 'Piccoli Piatti', 'From the Kitchen': 'Dalla Cucina', 'From the Grill': 'Alla Griglia',
  },
  pt: {
    'Starters': 'Entradas', 'Main Dishes': 'Pratos Principais', 'Desserts': 'Sobremesas', 'Beverages': 'Bebidas',
    'Salads': 'Saladas', 'Soup': 'Sopas', 'Appetizers': 'Aperitivos', 'Entrees': 'Pratos',
    'Sides': 'Acompanhamentos', 'Specials': 'Especialidades', 'Amuse-Bouche': 'Amuse-bouche',
    'Pizza & Pasta': 'Pizzas e Massas', 'Grill & BBQ': 'Grelhados e BBQ', 'Seafood': 'Frutos do Mar',
    'Vegetarian': 'Vegetariano', 'Kids Menu': 'Menu Infantil', 'Breakfast': 'Pequeno-almoço',
    'Lunch Specials': 'Menu do Dia', 'Dinner': 'Jantar', 'Happy Hour': 'Feliz Hora',
    "Chef's Recommendations": 'Recomendações do Chef', 'Seasonal Specials': 'Especialidades da Temporada',
    'Small Plates': 'Petitos Pratos', 'From the Kitchen': 'Da Cozinha', 'From the Grill': 'Da Grelha',
  },
  nl: {
    'Starters': 'Voorgerechten', 'Main Dishes': 'Hoofdgerechten', 'Desserts': 'Toetjes', 'Beverages': 'Dranken',
    'Salads': 'Salades', 'Soup': 'Soepen', 'Appetizers': 'Hapjes', 'Entrees': 'Hoofdgerechten',
    'Sides': 'Bijgerechten', 'Specials': 'Speciaaltjes', 'Amuse-Bouche': 'Amuse',
    'Pizza & Pasta': 'Pizza en Pasta', 'Grill & BBQ': 'Grill en BBQ', 'Seafood': 'Vis en Zeevruchten',
    'Vegetarian': 'Vegetarisch', 'Kids Menu': 'Kindermenu', 'Breakfast': 'Ontbijt',
    'Lunch Specials': 'Lunch Speciaal', 'Dinner': 'Avondeten', 'Happy Hour': 'Happy Hour',
    "Chef's Recommendations": 'Aanrader van de Chef', 'Seasonal Specials': 'Seizoensspecialiteiten',
    'Small Plates': 'Kleine Borden', 'From the Kitchen': 'Uit de Keuken', 'From the Grill': 'Van de Grill',
  },
  ru: {
    'Starters': 'Закуски', 'Main Dishes': 'Основные блюда', 'Desserts': 'Десерты', 'Beverages': 'Напитки',
    'Salads': 'Салаты', 'Soup': 'Супы', 'Appetizers': 'Закуски', 'Entrees': 'Горячее',
    'Sides': 'Гарниры', 'Specials': 'Специальное меню', 'Amuse-Bouche': 'Амюз-буш',
    'Pizza & Pasta': 'Пицца и Паста', 'Grill & BBQ': 'Гриль и BBQ', 'Seafood': 'Морепродукты',
    'Vegetarian': 'Вегетарианское', 'Kids Menu': 'Детское меню', 'Breakfast': 'Завтрак',
    'Lunch Specials': 'Дневное меню', 'Dinner': 'Ужин', 'Happy Hour': 'Счастливый час',
    "Chef's Recommendations": 'Рекомендации шеф-повара', 'Seasonal Specials': 'Сезонные блюда',
    'Small Plates': 'Маленькие порции', 'From the Kitchen': 'Из кухни', 'From the Grill': 'С гриля',
  },
};

/* ================================================================
   Food / Dish name translations — comprehensive menu item dictionary
   ================================================================ */
const DISH_TRANSLATIONS: Record<string, Record<string, string>> = {
  /* English dish names → target language */
  en: {},
  zh: {
    'Bruschetta': '意式烤面包片', 'Provoleta': '烤芝士饼', 'Gazpacho': '西班牙冷蔬菜汤',
    'Calamari Fritti': '炸鱿鱼圈', 'Paella': '西班牙海鲜饭', 'Grilled Ribeye Steak': '烤肋眼牛排',
    'Grilled Salmon': '香煎三文鱼', 'Tiramisu': '提拉米苏', 'Panna Cotta': '意式奶冻',
    'Espresso': '浓缩咖啡', 'Aperol Spritz': '阿佩罗橙光', 'Margherita Pizza': '玛格丽特披萨',
    'Caesar Salad': '凯撒沙拉', 'Pasta Carbonara': '培根奶油意面', 'Beef Steak': '牛排',
    'Chicken Parmesan': '帕玛森鸡排', 'Fish & Chips': '炸鱼薯条', 'Tomato Soup': '番茄汤',
    'French Fries': '炸薯条', 'Chocolate Lava Cake': '巧克力熔岩蛋糕', 'Cappuccino': '卡布奇诺',
    'French Onion Soup': '法式洋葱汤', 'Escargot': '法式焗蜗牛', 'Boeuf Bourguignon': '勃艮第红酒炖牛肉',
    'Duck Confit': '油封鸭腿', 'Crème Brûlée': '法式焦糖布丁', 'Foie Gras Torchon': '鹅肝慕斯卷',
  },
  es: {
    'Bruschetta': 'Bruschetta', 'Provoleta': 'Queso Provoleta a la parrilla', 'Gazpacho': 'Gazpacho',
    'Calamari Fritti': 'Calamares Fritos', 'Paella': 'Paella', 'Grilled Ribeye Steak': 'Entrecot a la Parrilla',
    'Grilled Salmon': 'Salmón a la Parrilla', 'Tiramisu': 'Tiramisú', 'Panna Cotta': 'Panna Cotta',
    'Espresso': 'Espresso', 'Aperol Spritz': 'Aperol Spritz', 'Margherita Pizza': 'Pizza Margarita',
    'Caesar Salad': 'Ensalada César', 'Pasta Carbonara': 'Pasta a la Carbonara', 'Beef Steak': 'Filete de Ternera',
    'Chicken Parmesan': 'Pollo Parmesano', 'Fish & Chips': 'Pescado con Papas Fritas', 'Tomato Soup': 'Sopa de Tomate',
    'French Fries': 'Papas Fritas', 'Chocolate Lava Cake': 'Pastel de Chocolate Fundido', 'Cappuccino': 'Capuchino',
    'French Onion Soup': 'Sopa de Cebolla Francesa', 'Escargot': 'Caracoles', 'Boeuf Bourguignon': 'Res al Borgoñón',
    'Duck Confit': 'Confit de Pato', 'Crème Brûlée': 'Crema Catalana (Brûlée)', 'Foie Gras Torchon': 'Foie Gras Torchon',
  },
  es: {
    'Bruschetta': 'Bruschetta',
    'Provoleta': 'Queso Provoleta a la parrilla',
    'Margherita Pizza': 'Pizza Margarita',
    'Caesar Salad': 'Ensalada César',
    'Pasta Carbonara': 'Pasta a la Carbonara',
    'Grilled Salmon': 'Salmón a la Parrilla',
    'Beef Steak': 'Filete de Ternera',
    'Chicken Parmesan': 'Pollo Parmesano',
    'Fish & Chips': 'Pescado con Papas Fritas',
    'Tomato Soup': 'Sopa de Tomate',
    'French Fries': 'Papas Fritas',
    'Chocolate Lava Cake': 'Pastel de Chocolate Fundido',
    'Tiramisu': 'Tiramisú',
    'Cappuccino': 'Capuchino',
    'Espresso': 'Espresso',
  },
  fr: {
    'Bruschetta': 'Bruschetta', 'Provoleta': 'Fromage Provoletta Grillé', 'Gazpacho': 'Gaspacho',
    'Calamari Fritti': 'Calamars Frits', 'Paella': 'Paëlla', 'Grilled Ribeye Steak': "Côte de Bœuf Grillée",
    'Grilled Salmon': 'Saumon Grillé', 'Tiramisu': 'Tiramisu', 'Panna Cotta': 'Panna Cotta',
    'Espresso': 'Espresso', 'Aperol Spritz': 'Spritz Aperol', 'Margherita Pizza': 'Pizza Margherita',
    'Caesar Salad': 'Salade César', 'Pasta Carbonara': 'Pâtes à la Carbonara', 'Beef Steak': 'Steak de Bœuf',
    'Chicken Parmesan': 'Poulet Parmigiana', 'Fish & Chips': 'Poisson Frites', 'Tomato Soup': 'Soupe de Tomates',
    'French Fries': 'Frites', 'Chocolate Lava Cake': 'Fondant au Chocolat', 'Cappuccino': 'Cappuccino',
    'French Onion Soup': "Soupe à l'Oignon", 'Escargot': 'Escargots', 'Boeuf Bourguignon': 'Bœuf Bourguignon',
    'Duck Confit': 'Confit de Canard', 'Crème Brûlée': 'Crème Brûlée', 'Foie Gras Torchon': "Foie Gras en Torchon",
  },
  de: {
    'Bruschetta': 'Bruschetta', 'Provoleta': 'Gegrillter Provoleta-Käse', 'Gazpacho': 'Gazpacho',
    'Calamari Fritti': 'Frittierte Kalamarie', 'Paella': 'Paella', 'Grilled Ribeye Steak': 'Gegrilltes Ribeye-Steak',
    'Grilled Salmon': 'Gebrillter Lachs', 'Tiramisu': 'Tiramisu', 'Panna Cotta': 'Panna Cotta',
    'Espresso': 'Espresso', 'Aperol Spritz': 'Aperol Spritz', 'Margherita Pizza': 'Margherita-Pizza',
    'Caesar Salad': 'Caesar-Salat', 'Pasta Carbonara': 'Pasta Carbonara', 'Beef Steak': 'Rindersteak',
    'Chicken Parmesan': 'Hähnchen Parmesan', 'Fish & Chips': 'Fisch mit Pommes', 'Tomato Soup': 'Tomatensuppe',
    'French Fries': 'Pommes Frites', 'Chocolate Lava Cake': 'Schokoladenkuchen', 'Cappuccino': 'Cappuccino',
    'French Onion Soup': 'Zwiebelsuppe', 'Escargot': 'Schnecken', 'Boeuf Bourguignon': 'Burgunder Rindsbraten',
    'Duck Confit': 'Ganskonfit', 'Crème Brûlée': 'Crème Brûlée', 'Foie Gras Torchon': 'Gänseleber-Torchon',
  },
  it: {
    'Bruschetta': 'Bruschetta', 'Provoleta': 'Formaggio Provoleta alla Griglia', 'Gazpacho': 'Gazpacho',
    'Calamari Fritti': 'Calamari Fritti', 'Paella': 'Paella', 'Grilled Ribeye Steak': 'Tagliata di Manzo',
    'Grilled Salmon': 'Salmone alla Griglia', 'Tiramisu': 'Tiramisù', 'Panna Cotta': 'Panna Cotta',
    'Espresso': 'Espresso', 'Aperol Spritz': 'Spritz Aperol', 'Margherita Pizza': 'Pizza Margherita',
    'Caesar Salad': 'Insalata Cesare', 'Pasta Carbonara': 'Pasta alla Carbonara', 'Beef Steak': 'Bistecca di Manzo',
    'Chicken Parmesan': 'Pollo alla Parmigiana', 'Fish & Chips': 'Pesce e Patatine', 'Tomato Soup': 'Zuppa di Pomodoro',
    'French Fries': 'Patatine Fritte', 'Chocolate Lava Cake': 'Torta al Cioccolato Fondente', 'Cappuccino': 'Cappuccino',
    'French Onion Soup': 'Zuppa di Cipolle Francese', 'Escargot': 'Lumache', 'Boeuf Bourguignon': 'Manzo alla Borgognona',
    'Duck Confit': 'Anatra in Confit', 'Crème Brûlée': 'Crema Bruciata', 'Foie Gras Torchon': 'Foie Gras in Torchon',
  },
  pt: {
    'Bruschetta': 'Bruschetta', 'Provoleta': 'Queijo Provoleta Grelhado', 'Gazpacho': 'Gazpacho',
    'Calamari Fritti': 'Calamares Fritos', 'Paella': 'Paella', 'Grilled Ribeye Steak': 'Ancho Grelhado',
    'Grilled Salmon': 'Salmão Grelhado', 'Tiramisu': 'Tiramisu', 'Panna Cotta': 'Panna Cotta',
    'Espresso': 'Espresso', 'Aperol Spritz': 'Aperol Spritz', 'Margherita Pizza': 'Pizza Margherita',
    'Caesar Salad': 'Salada César', 'Pasta Carbonara': 'Massa à Carbonara', 'Beef Steak': 'Bife de Carne',
    'Chicken Parmesan': 'Frango à Parmegiana', 'Fish & Chips': 'Peixe com Batatas', 'Tomato Soup': 'Sopa de Tomate',
    'French Fries': 'Batatas Fritas', 'Chocolate Lava Cake': 'Bolo de Chocolate Derretido', 'Cappuccino': 'Cappuccino',
    'French Onion Soup': 'Sopa de Cebola Francesa', 'Escargot': 'Caracois', 'Boeuf Bourguignon': 'Carne ao Vinho',
    'Duck Confit': 'Pato Confitado', 'Crème Brûlée': 'Crème Brûlée', 'Foie Gras Torchon': 'Foie Gras Torchon',
  },
  nl: {
    'Bruschetta': 'Bruschetta', 'Provoleta': 'Gegrilde Provoleta Kaas', 'Gazpacho': 'Gazpacho',
    'Calamari Fritti': 'Gebakken Inktvisringen', 'Paella': 'Paella', 'Grilled Ribeye Steak': 'Gegrild Ribeye',
    'Grilled Salmon': 'Gegrilde Zalm', 'Tiramisu': 'Tiramisu', 'Panna Cotta': 'Panna Cotta',
    'Espresso': 'Espresso', 'Aperol Spritz': 'Aperol Spritz', 'Margherita Pizza': 'Margherita Pizza',
    'Caesar Salad': 'Caesar Salade', 'Pasta Carbonara': 'Pasta Carbonara', 'Beef Steak': 'Rundvlees Biefstuk',
    'Chicken Parmesan': 'Kip Parmigiana', 'Fish & Chips': 'Vis met Friet', 'Tomato Soup': 'Tomatensoep',
    'French Fries': 'Frieten', 'Chocolate Lava Cake': 'Chocolade Lava Taart', 'Cappuccino': 'Cappuccino',
    'French Onion Soup': 'Uiensoep', 'Escargot': 'Slakken', 'Boeuf Bourguignon': 'Bourgondische Rundvleeschotel',
    'Duck Confit': 'Eendenconfit', 'Crème Brûlée': 'Crème Brûlée', 'Foie Gras Torchon': 'Foie Gras Torchon',
  },
  ru: {
    'Bruschetta': 'Брускетта', 'Provoleta': 'Жареный сыр Проволета', 'Gazpacho': 'Гаспачо',
    'Calamari Fritti': 'Жареные кальмары', 'Paella': 'Паэлья', 'Grilled Ribeye Steak': 'Стейк Рибай на гриле',
    'Grilled Salmon': 'Грильовый Лосось', 'Tiramisu': 'Тирамису', 'Panna Cotta': 'Панна Котта',
    'Espresso': 'Эспрессо', 'Aperol Spritz': 'Апероль Шприц', 'Margherita Pizza': 'Пицца Маргарита',
    'Caesar Salad': 'Салат Цезарь', 'Pasta Carbonara': 'Паста Карбонара', 'Beef Steak': 'Стейк из Говядины',
    'Chicken Parmesan': 'Курица Пармиджана', 'Fish & Chips': 'Рыба с Картофелем Фри', 'Tomato Soup': 'Томатный Суп',
    'French Fries': 'Картошка Фри', 'Chocolate Lava Cake': 'Шоколадный Лава Кейк', 'Cappuccino': 'Капучино',
    'French Onion Soup': 'Луковый Суп', 'Escargot': 'Улитки', 'Boeuf Bourguignon': 'Говядина по-бургундски',
    'Duck Confit': 'Утка Конфи', 'Crème Brûlée': 'Крем Брюле', 'Foie Gras Torchon': 'Фуа Гра Торошон',
  },
  zh: {
    'Bruschetta': '意式烤面包片',
    'Provoleta': '烤芝士饼',
    'Margherita Pizza': '玛格丽特披萨',
    'Caesar Salad': '凯撒沙拉',
    'Pasta Carbonara': '培根奶油意面',
    'Grilled Salmon': '香煎三文鱼',
    'Beef Steak': '牛排',
    'Chicken Parmesan': '帕玛森鸡排',
    'Fish & Chips': '炸鱼薯条',
    'Tomato Soup': '番茄汤',
    'French Fries': '炸薯条',
    'Chocolate Lava Cake': '巧克力熔岩蛋糕',
    'Tiramisu': '提拉米苏',
    'Cappuccino': '卡布奇诺',
    'Espresso': '浓缩咖啡',
  },
  ja: {
    'Bruschetta': 'ブルスケッタ', 'Provoleta': 'プロボレータチーズグリル', 'Gazpacho': 'ガスパチョ',
    'Calamari Fritti': 'フリット・カラマリ', 'Paella': 'パエリア', 'Grilled Ribeye Steak': 'リブローステーキ',
    'Grilled Salmon': '鮭のグリル', 'Tiramisu': 'ティラミス', 'Panna Cotta': 'パンナコッタ',
    'Espresso': 'エスプレッソ', 'Aperol Spritz': 'アペロール スプリッツ', 'Margherita Pizza': 'マルゲリータピザ',
    'Caesar Salad': 'シーザーサラダ', 'Pasta Carbonara': 'カルボナーラパスタ', 'Beef Steak': 'ビーフステーキ',
    'Chicken Parmesan': 'チキンパルメジャーノ', 'Fish & Chips': 'フィッシュ＆チップス', 'Tomato Soup': 'トマトスープ',
    'French Fries': 'フライドポテト', 'Chocolate Lava Cake': 'チョコレートラバーケイキ', 'Cappuccino': 'カプチーノ',
    'French Onion Soup': 'フレンチオニオンスープ', 'Escargot': 'エスカルゴ', 'Boeuf Bourguignon': 'ブーフ・ブルギニョン',
    'Duck Confit': 'コンフィ・ド・カナール', 'Crème Brûlée': 'クレーム・ブリュレ', 'Foie Gras Torchon': 'フォアグラ トゥルション',
  },
  ko: {
    'Bruschetta': '브루스케타', 'Provoleta': '프로볼레타 치즈 그릴', 'Gazpacho': '가스파초',
    'Calamari Fritti': '튀긴 오징어 링', 'Paella': '파에야', 'Grilled Ribeye Steak': '그릴 리브아이 스테이크',
    'Grilled Salmon': '구운 연어 스테이크', 'Tiramisu': '티라미수', 'Panna Cotta': '판나코타',
    'Espresso': '에스프레소', 'Aperol Spritz': '아페롤 스프릿츠', 'Margherita Pizza': '마르게리타 피자',
    'Caesar Salad': '시저 샐러드', 'Pasta Carbonara': '카르보나라 파스타', 'Beef Steak': '소고기 스테이크',
    'Chicken Parmesan': '치킨 파르메산', 'Fish & Chips': '피쉬 앤 칩스', 'Tomato Soup': '토마토 수프',
    'French Fries': '감자튀김', 'Chocolate Lava Cake': '초코렛 라바 케이크', 'Cappuccino': '카푸치노',
    'French Onion Soup': '프렌치 양파 스프', 'Escargot': '에스카르고', 'Boeuf Bourguignon': '부르고뉴 소고기 찜',
    'Duck Confit': '오리 콩피', 'Crème Brûlée': '크림 브륄레', 'Foie Gras Torchon': '푸아그라 토숑',
  },
  ar: {
    'Bruschetta': 'بروشيتا', 'Provoleta': 'جبنة بروفوليتا مشوية', 'Gazpacho': 'جاسباتشو',
    'Calamari Fritti': 'حبار مقلي', 'Paella': 'بايلا', 'Grilled Ribeye Steak': 'ستيك ريباي مشوي',
    'Grilled Salmon': 'سلمون مشوي', 'Tiramisu': 'تييراميسو', 'Panna Cotta': 'بانا كوتا',
    'Espresso': 'إسبريسو', 'Aperol Spritz': 'أبيرول سبريتز', 'Margherita Pizza': 'بيتزا مارغريتا',
    'Caesar Salad': 'سلطة قيصر', 'Pasta Carbonara': 'باستا كاربونارا', 'Beef Steak': 'ستيك لحم بقري',
    'Chicken Parmesan': 'دجج بارميجان', 'Fish & Chips': 'سمك مع بطاطس مقلية', 'Tomato Soup': 'شوربة الطماطم',
    'French Fries': 'بطاطس مقلية', 'Chocolate Lava Cake': 'كيك الشوكولاتة المنصهرة', 'Cappuccino': 'كابتشينو',
    'French Onion Soup': 'شوربة البصل الفرنسية', 'Escargot': 'حلزون', 'Boeuf Bourguignon': 'لحم بقر burgundy',
    'Duck Confit': 'بط كونفي', 'Crème Brûlée': 'كريم بروليه', 'Foie Gras Torchon': 'فوا جرا تورشون',
  },
};

function translateDishText(original: string, langDict: Record<string, string> | undefined): string | undefined {
  if (!langDict) return undefined;
  return langDict[original] || undefined;
}

/* ================================================================
   Dish description translations — common dish descriptions
   ================================================================ */
const DESC_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {},
  zh: {
    'Melted provolone cheese with oregano and sun-dried tomatoes.': '融化普罗卧干酪配牛至和番茄干。',
    'Traditional cold soup of tomato, cucumber, and pepper.': '番茄、黄瓜、辣椒制成的传统冷汤。',
    'Grilled bread topped with fresh tomatoes, basil, garlic and olive oil.': '烤面包片配新鲜番茄、罗勒、蒜蓉和橄榄油。',
    'Crispy fried squid rings served with lemon aioli.': '酥脆炸鱿鱼圈，搭配柠檬蛋黄酱。',
    'Rice with chicken, rabbit, green beans, and saffron.': '鸡肉、兔肉、四季豆和藏红花烩饭。',
    '300g grass-fed ribeye, truffle mashed potatoes, grilled asparagus.': '300g 草饲肋眼牛排，松露土豆泥，烤芦笋。',
    'Atlantic salmon fillet with lemon butter sauce and seasonal vegetables.': '大西洋鲑鱼排配柠檬黄油酱和时蔬。',
    'Classic Italian dessert with mascarpone, espresso and cocoa.': '经典意式甜点，马斯卡彭芝士、浓缩咖啡和可可粉。',
    'Silky cream dessert with fresh berry compote.': '丝滑奶冻配新鲜莓果酱。',
    'Double shot of our house-roasted Italian blend.': '双份自家烘焙意大利拼配浓缩咖啡。',
    'Aperol, prosecco, soda, fresh orange slice.': '阿佩罗酒、普罗塞克气泡酒、苏打水、新鲜橙子切片。',
  },
  es: {
    'Melted provolone cheese with oregano and sun-dried tomatoes.': 'Queso provolone derretido con orégano y tomates secos.',
    'Traditional cold soup of tomato, cucumber, and pepper.': 'Sopa fría tradicional de tomate, pepino y pimiento.',
    'Grilled bread topped with fresh tomatoes, basil, garlic and olive oil.': 'Pan tostado con tomate fresco, albahaca, ajo y aceite de oliva.',
    'Crispy fried squid rings served with lemon aioli.': 'Anillos de calamar fritos crujientes con alioli de limón.',
    'Rice with chicken, rabbit, green beans, and saffron.': 'Arroz con pollo, conejo, judías verdes y azafrán.',
    '300g grass-fed ribeye, truffle mashed potatoes, grilled asparagus.': 'Entrecot de 300g de pasto, puré de trufa, espárragos a la plancha.',
    'Atlantic salmon fillet with lemon butter sauce and seasonal vegetables.': 'Filete de salmón del Atlántico con salsa de mantequilla de limón y verduras de temporada.',
    'Classic Italian dessert with mascarpone, espresso and cocoa.': 'Postre italiano clásico con mascarpone, expresso y cacao.',
    'Silky cream dessert with fresh berry compote.': 'Postre de crema sedosa con compota de bayas frescas.',
    'Double shot of our house-roasted Italian blend.': 'Doble dosis de nuestra mezcla italiana tostada en casa.',
    'Aperol, prosecco, soda, fresh orange slice.': 'Aperol, prosecco, soda, rodaja de naranja fresca.',
  },
  fr: {
    'Melted provolone cheese with oregano and sun-dried tomatoes.': 'Fromage provolone fondu à l\'origan et tomates séchées.',
    'Traditional cold soup of tomato, cucumber, and pepper.': 'Soupe froide traditionnelle de tomate, concombre et poivron.',
    'Grilled bread topped with fresh tomatoes, basil, garlic and olive oil.': 'Pain grillé garni de tomates fraîches, basilic, ail et huile d\'olive.',
    'Crispy fried squid rings served with lemon aioli.': 'Anneaux de calamars frits croustillants à l\'ail au citron.',
    'Rice with chicken, rabbit, green beans, and saffron.': 'Riz au poulet, lapin, haricots verts et safran.',
    '300g grass-fed ribeye, truffle mashed potatoes, grilled asparagus.': "Côte de bœuf 300g herbage, purée à la truffe, asperges grillées.",
    'Atlantic salmon fillet with lemon butter sauce and seasonal vegetables.': 'Filet de saumon de l\'Atlantique, sauce beurre citron et légumes de saison.',
    'Classic Italian dessert with mascarpone, espresso and cocoa.': 'Dessert italien classique au mascarpone, expresso et cacao.',
    'Silky cream dessert with fresh berry compote.': 'Dessert crémeux onctueux aux fruits rouges frais.',
    'Double shot of our house-roasted Italian blend.': 'Double dose de notre mélange italien torréfié maison.',
    'Aperol, prosecco, soda, fresh orange slice.': 'Aperol, prosecco, soda, tranche d\'orange frais.',
  },
  de: {
    'Melted provolone cheese with oregano and sun-dried tomatoes.': 'Geschmolzener Provolone mit Oregano und getrockneten Tomaten.',
    'Traditional cold soup of tomato, cucumber, and pepper.': 'Traditionelle kalte Suppe aus Tomate, Gurke und Paprika.',
    'Grilled bread topped with fresh tomatoes, basil, garlic and olive oil.': 'Gegrilltes Brot mit frischen Tomaten, Basilikum, Knoblauch und Olivenöl.',
    'Crispy fried squid rings served with lemon aioli.': 'Knusprig frittierte Tintenfischringe mit Zitronen-Aioli.',
    'Rice with chicken, rabbit, green beans, and saffron.': 'Reis mit Huhn, Kaninchen, grünen Bohnen und Safran.',
    '300g grass-fed ribeye, truffle mashed potatoes, grilled asparagus.': '300g Ribeye von Weiderindern, Trüffelkartoffelbrei, gegrillter Spargel.',
    'Atlantic salmon fillet with lemon butter sauce and seasonal vegetables.': 'Atlantischer Lachsfilet mit Zitronenbuttersauce und saisonalem Gemüse.',
    'Classic Italian dessert with mascarpone, espresso and cocoa.': 'Klassisches italienisches Dessert mit Mascarpone, Espresso und Kakao.',
    'Silky cream dessert with fresh berry compote.': 'Seidiges Creme-Dessert mit frischem Beerenkompott.',
    'Double shot of our house-roasted Italian blend.': 'Doppelter Schuss unserer hausgerösteten italienischen Mischung.',
    'Aperol, prosecco, soda, fresh orange slice.': 'Aperol, Prosecco, Soda, frische Orangenscheibe.',
  },
  ja: {
    'Melted provolone cheese with oregano and sun-dried tomatoes.': '溶けたプロボローネチーズにオレガノとドライトマトのせ。',
    'Traditional cold soup of tomato, cucumber, and pepper.': 'トマト、キュウリ、ピーマンの伝統的な冷製スープ。',
    'Grilled bread topped with fresh tomatoes, basil, garlic and olive oil.': '新鮮なトマト、バジル、ニンニク、オリーブオイルをのせたグリルパン。',
    'Crispy fried squid rings served with lemon aioli.': 'レモンアヨリ添えのサクサク揚げイカリング。',
    'Rice with chicken, rabbit, green beans, and saffron.': 'チキン、ラビット、インゲン、サフランを使ったライス。',
    '300g grass-fed ribeye, truffle mashed potatoes, grilled asparagus.': '300gグラスフェッドリブローステーキ、トリュフマッシュポテト、グリルアスパラガス。',
    'Atlantic salmon fillet with lemon butter sauce and seasonal vegetables.': '大西洋サーモンフィレにレモンバターソースと季節の野菜。',
    'Classic Italian dessert with mascarpone, espresso and cocoa.': 'マスカルポーネ、エスプレッソ、ココアを使ったクラシックイタリアンスイーツ。',
    'Silky cream dessert with fresh berry compote.': '新鮮なベリーのコンポートを添えたシルキークリームデザート。',
    'Double shot of our house-roasted Italian blend.': '当店自慢のハウスローストイタリアンブレンドのダブルショット。',
    'Aperol, prosecco, soda, fresh orange slice.': 'アペロール、プロセッコ、ソーダ、新鮮なオレンジスライス。',
  },
  ko: {
    'Melted provolone cheese with oregano and sun-dried tomatoes.': '녹아내린 프로볼론 치즈에 오레가노와 말린 토마토.',
    'Traditional cold soup of tomato, cucumber, and pepper.': '토마토, 오이, 고추로 만든 전통적인 차가운 수프.',
    'Grilled bread topped with fresh tomatoes, basil, garlic and olive oil.': '신선한 토마토, 바질, 마늘, 올리브 오일을 얹은 그릴 빵.',
    'Crispy fried squid rings served with lemon aioli.': '레몬 아욜리 곁들인 바삭한 튀김 오징어 링.',
    'Rice with chicken, rabbit, green beans, and saffron.': '닭고기, 토끼고기, 강낭콩, 샤프란을 넣은 쌀밥.',
    '300g grass-fed ribeye, truffle mashed potatoes, grilled asparagus.': '300g 방목 소 리브아이 스테이크, 트러플 으깬 감자, 그릴 아스파라거스',
    'Atlantic salmon fillet with lemon butter sauce and seasonal vegetables.': '대서양 연어 필레에 레몬 버터 소스와 계절 채소.',
    'Classic Italian dessert with mascarpone, espresso and cocoa.': '마스카르포네, 에스프레소, 코코아를 사용한 클래식 이탈리안 디저트.',
    'Silky cream dessert with fresh berry compote.': '신선한 베리 컴포트를 곁들인 실키 크림 디저트.',
    'Double shot of our house-roasted Italian blend.': '우리 매장에서 직접 로스트한 이탈리안 블렌드 더블샷.',
    'Aperol, prosecco, soda, fresh orange slice.': '아페롤, 프로세코, 소다, 신선한 오렌지 슬라이스.',
  },
};

/* ================================================================
   Context definition
   ================================================================ */
/** Shape of dish-level AI translations stored on Dish.translations[langCode] */
interface DishTranslationEntry {
  name?: string;
  description?: string;
}

interface LanguageContextValue {
  uiLang: string;
  restaurantLang: string;
  setUiLang: (code: string) => void;
  setRestaurantLang: (code: string) => void;
  t: (key: keyof Translations, ...args: (string | number)[]) => string;
  tTag: (englishTag: string) => string;
  tSection: (name: string, sectionTranslations?: Record<string, string>) => { original: string; translated?: string; display: string };
  tDishName: (name: string, dishTranslations?: Record<string, DishTranslationEntry>) => { original: string; translated?: string; display: string };
  tDesc: (desc: string, dishTranslations?: Record<string, DishTranslationEntry>) => { original: string; translated?: string; display: string };
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

/* ================================================================
   Provider
   ================================================================ */
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [uiLang, setUiLangState] = useState(() => {
    try {
      return localStorage.getItem('menukits-ui-lang') || 'en';
    } catch {
      return 'en';
    }
  });
  const [restaurantLang, setRestaurantLangState] = useState('en');

  const setUiLang = useCallback((code: string) => {
    setUiLangState(code);
    try { localStorage.setItem('menukits-ui-lang', code); } catch {}
  }, []);

  const setRestaurantLang = useCallback((code: string) => {
    setRestaurantLangState(code);
  }, []);

  const t = useCallback((key: keyof Translations, ...args: (string | number)[]): string => {
    const tr = getTranslations(uiLang);
    let str = tr[key];
    for (let i = 0; i < args.length; i++) {
      str = str.replace(`{${i}}`, String(args[i]));
    }
    return str;
  }, [uiLang]);

  const tTag = useCallback((englishTag: string): string => {
    const tr = getTranslations(uiLang);
    const map: Partial<Record<string, keyof Translations>> = {
      /* Dietary tags */
      'Vegan': 'vegan',
      'Vegetarian': 'vegetarian',
      'Gluten-free': 'glutenFree',
      'Lactose-free': 'lactoseFree',
      'Dairy-free': 'dairyFree',
      'Spicy': 'spicy',
      /* Allergens */
      'Gluten': 'allergenGluten',
      'Peanuts': 'allergenPeanuts',
      'Eggs': 'allergenEggs',
      'Fish': 'allergenFish',
      'Crustaceans': 'allergenCrustaceans',
      'Soybeans': 'allergenSoybeans',
      'Milk': 'allergenMilk',
      'Nuts': 'allergenNuts',
      'Celery': 'allergenCelery',
      'Mustard': 'allergenMustard',
      'Sesame': 'allergenSesame',
      'Sulfites': 'allergenSulfites',
      'Lupin': 'allergenLupin',
      'Molluscs': 'allergenMolluscs',
    };
    const mappedKey = map[englishTag];
    if (!mappedKey) return englishTag;
    const translated = tr[mappedKey];
    if (uiLang === restaurantLang || !translated || translated === englishTag) {
      return englishTag;
    }
    return `${englishTag} / ${translated}`;
  }, [uiLang, restaurantLang]);

  /* Bilingual section name — checks AI translations first, then dictionary fallback */
  const tSection = useCallback((name: string, sectionTranslations?: Record<string, string>) => {
    const isSameLang = uiLang === restaurantLang;
    if (!isSameLang && sectionTranslations?.[uiLang]) {
      return { original: name, translated: sectionTranslations[uiLang], display: `${name} / ${sectionTranslations[uiLang]}` };
    }
    // Dictionary fallback
    const dict = SECTION_TRANSLATIONS[uiLang];
    const translated = translateDishText(name, dict);
    return {
      original: name,
      translated: isSameLang ? undefined : (translated || undefined),
      display: isSameLang ? name : (translated || name),
    };
  }, [uiLang, restaurantLang]);

  /* Bilingual dish name — checks AI translations first, then dictionary fallback */
  const tDishName = useCallback((name: string, dishTranslations?: Record<string, DishTranslationEntry>) => {
    const isSameLang = uiLang === restaurantLang;
    if (!isSameLang && dishTranslations?.[uiLang]?.name) {
      return { original: name, translated: dishTranslations[uiLang].name!, display: `${name} / ${dishTranslations[uiLang].name!}` };
    }
    // Dictionary fallback
    const dict = DISH_TRANSLATIONS[uiLang];
    const translated = translateDishText(name, dict);
    return {
      original: name,
      translated: isSameLang ? undefined : (translated || undefined),
      display: isSameLang ? name : (translated ? `${name} / ${translated}` : name),
    };
  }, [uiLang, restaurantLang]);

  /* Bilingual description — checks AI translations first, then dictionary fallback */
  const tDesc = useCallback((desc: string, dishTranslations?: Record<string, DishTranslationEntry>) => {
    const isSameLang = uiLang === restaurantLang;
    if (!isSameLang && dishTranslations?.[uiLang]?.description) {
      return { original: desc, translated: dishTranslations[uiLang].description!, display: `${desc} / ${dishTranslations[uiLang].description!}` };
    }
    // Dictionary fallback
    const dict = DESC_TRANSLATIONS[uiLang];
    const translated = translateDishText(desc, dict);
    return {
      original: desc,
      translated: isSameLang ? undefined : (translated || undefined),
      display: isSameLang ? desc : (translated ? `${desc} / ${translated}` : desc),
    };
  }, [uiLang, restaurantLang]);

  return (
    <LanguageContext.Provider value={{ uiLang, restaurantLang, setUiLang, setRestaurantLang, t, tTag, tSection, tDishName, tDesc }}>
      {children}
    </LanguageContext.Provider>
  );
}

/* ================================================================
   Hook
   ================================================================ */
export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
